### ISSUE TITLE
Support embedding iframes with for example relevant graphs from grafana

### ISSUE THREAD

**Issue by nervetattoo** [nervetattoo/simple-thermostat#1]
Proposed config syntax:

```yaml
- type: custom:better-thermostat
   entity: climate.kjkken
   embeds:
     - url: <url>
        ratio: 50%
     - url: <url>
        ratio: 50%
```

Embeds should probably be rendered in a wrapped grid with 1 or 2 items pr row
