### ISSUE TITLE
icon not working as expected

### ISSUE THREAD

**Issue by DrJohnT** [nervetattoo/simple-thermostat#107]
In the documentation it says 

- icon string|object:

yet if I provide an object, the control does not inherit the icon of that control.  e.g. 

```yaml
  entity: climate.wiser_upstairs
  name: Upstairs
  icon: climate.wiser_upstairs
  type: 'custom:simple-thermostat'
  fallback: 0
  decimals: 0
  step_layout: row
  step_size: 1
  control:
    - hvac
```

I tried this too, but no icon displayed.
```yaml
  entity: climate.wiser_upstairs
  name: Upstairs
  type: 'custom:simple-thermostat'
  icon:
    - idle: 'mdi:radiator-disabled'
    - heating: 'mdi:radiator'
  fallback: 0
  ...
```

I tried this too, but no icon displayed.
```yaml
  entity: climate.wiser_upstairs
  name: Upstairs
  type: 'custom:simple-thermostat'
  icon: true
  fallback: 0
  ...
```

This does work, but the icon does not change when the radiator is on.
```yaml
  entity: climate.wiser_upstairs
  name: Upstairs
  type: 'custom:simple-thermostat'
  icon: mdi:radiator-disabled
  fallback: 0
  ...
```
What is the syntax?

**Comment by nervetattoo** [comment]
You almost had it in your second example, except you passed a _list of objects_ not a single object. Try this:

```yaml
entity: climate.wiser_upstairs
name: Upstairs
type: 'custom:simple-thermostat'
icon:
  idle: 'mdi:radiator-disabled'
  heating: 'mdi:radiator'
```

**Comment by DrJohnT** [comment]
Even with the correct syntax, the icon does not appear :-(

```yaml
type: 'custom:simple-thermostat'
icon:
  idle: 'mdi:radiator-disabled'
  heating: 'mdi:radiator'
control:
  hvac:
    auto: false
decimals: 0
entity: climate.wiser_lounge
fallback: 0
name: Lounge
step_layout: row
step_size: 1
```
