### ISSUE TITLE
Missing mode labels

### ISSUE THREAD

**Issue by 2bithacker** [nervetattoo/simple-thermostat#108]
Using simple-thermostat 0.34.1, if I configure `controls` as a dict, I lose the mode labels on the panel ("Operation", "Fan Mode", etc) and setting the `_name` key doesn't seem to cause any change in the behavior.

```
control:
  hvac:
    _name: Operation
    cool: false
    auto: false
  fan:
    _name: Fan Mode
    'on':
      icon: 'mdi:fan'
decimals: 0
entity: climate.home
step-size: 1
step_layout: row
type: 'custom:simple-thermostat'
```
results in
![Screenshot from 2020-02-21 12-01-42](https://user-images.githubusercontent.com/1847654/75067513-0d222c80-54a2-11ea-8f1c-c6b64f6d70da.png)

If I configure `control` as a list instead, like so:

```
control:
  - hvac
  - fan
decimals: 0
entity: climate.home
step-size: 1
step_layout: row
type: 'custom:simple-thermostat'
```
then I do get the labels:
![Screenshot from 2020-02-21 12-02-16](https://user-images.githubusercontent.com/1847654/75067560-262add80-54a2-11ea-99a2-5b85139abd46.png)

Not sure if I'm doing something wrong. I'm just trying to hide the "Cool" and "Auto" buttons for Operation, as I don't have an AC system, just a forced hot air furnace, but I'd like to keep the "Operation" and "Fan Mode" labels on the buttons, as I think it makes their purpose clearer.
