### ISSUE TITLE
icon colours

### ISSUE THREAD

**Issue by jchasey** [nervetattoo/simple-thermostat#11]
The default icon colours appear to be in grey as opposed to matching the existing theme.

Separately it would be good to optionally change the colour depending on state.
e.g. Leave as standard for radiator-disabled, red for radiator (ie warming).

**Comment by nervetattoo** [comment]
Would you prefer custom colors for states or a predefined set?
I guess a more flexible and complex configuration can be supported:

```yaml
icons:
  heat:
    icon: <icon>
    color: <color>
```
