### ISSUE TITLE
Enhancement request: tap_action for sensors

### ISSUE THREAD

**Issue by flyboy013** [nervetattoo/simple-thermostat#111]
I use the simple-thermostat for several HVAC and heated floor systems.  My use of the cards includes the display of several sensor states such as current mode (heating, cooling, idle, etc) as well as current temperature.  Currently if I click on the these sensor values, home assistant displays a history graph.  I'd like the ability to have a tap_action so that I can instead display a grafana graph as grafana provide both better performance and graphing capabilities.  I would like to define something like this:

```
          - type: 'custom:simple-thermostat'
            name: Kitchen
            sensors:
              - name: Now
                entity: sensor.ambient_temp_1
                tap_action:
                  action: url
                    url_path: /graph/d/Ub60_lWRz/temperatures?orgId=1&var-zones=Kitchen
              - name: Status
                entity: sensor.living_room_zone_status
                tap_action:
                  action: url
                    url_path: /graph/d/MLn82eRgk/hvac?orgId=1
```

![image](https://user-images.githubusercontent.com/44688061/75288368-3c120880-57ea-11ea-9be1-42505184cf65.png)

It looks like there was a [request](https://github.com/nervetattoo/simple-thermostat/issues/95) for this capability along with the compact mode, but it would appear the request was closed when the compact mode was implemented.
