### ISSUE TITLE
hide not working?

### ISSUE THREAD

**Issue by wivaku** [nervetattoo/simple-thermostat#119]
I have the following (using v0.34.1):
```
        - type: custom:simple-thermostat
          entity: climate.office
          hide:
            - state: true
              temperature: false
```
Would expect that either `state` or `temperature` are not shown.
But I see both.
