### ISSUE TITLE
support attribute as well as a sensor

### ISSUE THREAD

**Issue by jchasey** [nervetattoo/simple-thermostat#12]
Rather than just supporting sensors, it would be useful to be able to support the attribute of a sensor also. Reason is that many temperature sensors will also report humidity and this would avoid the need to pull it out as an additional template sensor.

**Comment by nervetattoo** [comment]
This makes sense. A simple way to configure it would be to add some flexibility to the `sensors` array:

```yaml
sensors:
  - entity: <entityid>
  - attribute: <attributename>
```

Should be a small addition and I'll look into it when I sit down and hack on the card unless someone else beats me to it ;)
