### ISSUE TITLE
[Bug] Incorrect Label / Translations Not Loading on 0.109.x

### ISSUE THREAD

**Issue by ronaldheft** [nervetattoo/simple-thermostat#122]
HomeAssistant is migrating to a new translation system, and it looks like there are some spots where the translations aren't loading on 0.109. Note the operations buttons, particularly `heat_cool`:

<img width="385" alt="Screen Shot 2020-05-11 at 1 05 06 PM" src="https://user-images.githubusercontent.com/1143112/81590539-f0064700-9388-11ea-8974-4d7fe8e5ac08.png">

**Comment by Andream69** [comment]
Good morning, two requests. The first, if possible to translate the highlighted texts, the second if they can be customized. Type: "Current temperature" or "Real temperature". Thanks.
![Annotazione 2020-05-13 075117](https://user-images.githubusercontent.com/59484530/81776678-848ab980-94ef-11ea-8531-d16ec98564a7.png)

**Comment by edenhaus** [comment]
> Good morning, two requests. The first, if possible to translate the highlighted texts, the second if they can be customized. Type: "Current temperature" or "Real temperature". And "State" with "Stato". Thanks.
> ![Annotazione 2020-05-13 075117](https://user-images.githubusercontent.com/59484530/81776678-848ab980-94ef-11ea-8531-d16ec98564a7.png)

You can already translate manually the temperature and state. You have to specify the `label` in your config.
Below an example:
```
control:
  _headings: false
  preset:
    away: true
    none:
      name: Normal
entity: climate....
label:
  state: stato # insert here your translation for the state
  temperature: temperatura attuale # insert here your translation for the temperature
step_layout: row
type: 'custom:simple-thermostat'
```
