### ISSUE TITLE
Apply "decimals" also for "sensors"

### ISSUE THREAD

**Issue by CodeFinder2** [nervetattoo/simple-thermostat#137]
When I specify `decimals: 1`, the temperature and humidity of my sensors are still shown with two decimal places. Is this intended? 🙈 

Edit: here's the code:
```yaml
type: 'custom:simple-thermostat'
entity: climate.0x00158d000xxx_climate
step_size: 1
name: Bad
decimals: 1
sensors:
  - entity: sensor.0x00158d000xxx_temperature
    name: Raum
    decimals: 1
  - entity: sensor.0x00158d000xxx_humidity
    name: Feuchtigkeit
label:
  temperature: Heizkörper
```
