### ISSUE TITLE
Configure icons for the tiles in the Operation section?

### ISSUE THREAD

**Issue by ha14937** [nervetattoo/simple-thermostat#139]
Is it possible to configure icons for the tiles in the Operation section?

![image](https://user-images.githubusercontent.com/56581105/85924687-e6b23a80-b861-11ea-9b0e-84abdc32180a.png)

**Comment by nervetattoo** [comment]
You can do:
```yaml
control:
  hvac:
    "off":
      icon: mdi:cupcake
```
... and so on
