### ISSUE TITLE
Preset handling - highlight when 'preset' set to 'none'

### ISSUE THREAD

**Issue by jbcodemonkey** [nervetattoo/simple-thermostat#144]
'Preset' allows quick setting of modes and to toggle the button status accordingly.

My [honeywell thermostat](https://www.home-assistant.io/integrations/honeywell/) has a two Preset states: 'away' and 'none'.

I have the card configured this way:
```
  preset:
    _name: Location
    away:
      icon: 'mdi:home-outline'
    none:
      icon: 'mdi:home'
      name: Home
```

Issue:
'Away' button activates away preset state on and highlights the button accordingly.
'Home' button sets preset to 'none' but never highlights.

Desired behavior:
1: Use a single button 'Away' to toggle preset state between 'away' and 'none'.
OR
2: Highlight 'None' state button when state is 'none'

Please let me know if this makes sense. I love this thermostat card, just trying to add an Away toggle so the display matches the condition. If my thermostat had a state 'home', I think this would already work.
