### ISSUE TITLE
Custom element doesn't exist

### ISSUE THREAD

**Issue by atomicpapa** [nervetattoo/simple-thermostat#15]
I am getting the big red box of doom with this card.

**Custom element doesn't exist: simple-thermostat**

 Config as follows:

ui.lovelace.yaml

```
resources:
  - url: /local/simple-thermostat/simple-thermostat.js?v=1
    type: module
```

```
  - id: 4
    icon: mdi:weather-sunset
    title: Weather
    background: center / cover no-repeat url("/local/galaxy-wallpaper-21.jpg") fixed
    cards:
      - id: 60
        type: vertical-stack
        cards:
          - id: 61
            type: weather-forecast
            entity: weather.dark_sky
          - id: 62
            type: horizontal-stack
            cards:
              - id: 62a
                type: "custom:mini-graph-card"
                name: Temp
                entity: sensor.dark_sky_temperature
                # labels: true
                hours_to_show: 168
                # line_width: 3
              - id: 62b
                type: "custom:mini-graph-card"
                name: Humidity
                entity: sensor.dark_sky_humidity
                hours_to_show: 168
          - id: 63
            type: horizontal-stack
            cards:
              - id: 63a
                type: "custom:mini-graph-card"
                name: Pressure
                entity: sensor.dark_sky_pressure
              - id: 63b
                type: "custom:mini-graph-card"
                name: Wind Speed
                entity: sensor.dark_sky_wind_speed

      - type: custom:simple-thermostat
        entity: climate.thermostat
        step_size: 1
        sensors:
          - sensor.inside_temp
```
file is named correctly and in the correct location

**Comment by dustins1983** [comment]
I have noticed if you dont click download RAW file for the .js it will do this. Have you tried that

**Comment by nervetattoo** [comment]
Your config looks slightly off for `sensors`, you need to specify an array of attributes like so:
```yaml
      - type: custom:simple-thermostat
        entity: climate.thermostat
        step_size: 1
        sensors:
          - entity: sensor.inside_temp
```

Notice `- entity: <id>` and not just `- <id>`

**Comment by bhaap** [comment]
Same issue here.

The component worked for three days and tonight it died:

```
      - type: custom:simple-thermostat
        entity: climate.varme_huset
        name: Termostat huset
        hide:
          mode: true
```

<img width="394" alt="skarmavbild 2019-01-15 kl 09 37 05" src="https://user-images.githubusercontent.com/2168003/51168321-3472f700-18a9-11e9-9814-9296a4c5116c.png">

**Comment by essell** [comment]
I just had the same issue as @bhaap happen to me randomly tonight after working fine for a couple days. I loved this custom card, anyone else running into the same issue or have any troubleshooting advice?

Browser:
Chrome Version 71.0.3578.98 (Official Build) (64-bit) -- on macOS
Did recently run some system updates.

@bhaap Was there any correlating system updates you might have done? I wonder if there was some upgrade to WebKit or something else externally that could have broken things.

**Comment by fredrike** [comment]
I saw this in the browser console: `94b8ff6408c67f36c506.chunk.js:5759 Uncaught (in promise) /local/custom-lovelace/simple-thermostat.js?v=2`

**Comment by essell** [comment]
How many Swedes can we get on this issue.

**Comment by essell** [comment]
> I saw this in the browser console: `94b8ff6408c67f36c506.chunk.js:5759 Uncaught (in promise) /local/custom-lovelace/simple-thermostat.js?v=2`

Just confirmed the same message in console

**Comment by essell** [comment]
Great insight from @thomasloven on Home Assistant community forum:

Unpkg - a repository of javascript packages seems to be having problems currently.
Many custom cards link directly to their hosted version of the package and that’s why they all have trouble at the same time.

Home Assistant includes its own packaged version of the LitElement and some cards have already been updated to piggy-back onto that one instead.

Have patience. Some cards will be fixed, and unpkg will probably go up again soon - this isn’t the first time…

----

So, perhaps a change to use the HA-bundled lit-element at some point could be helpful.

**Comment by thomasloven** [comment]
#16

**Comment by essell** [comment]
woooot. Just saw that. Does tracker.json need an update? I actually don't know but I'm assuming it does--for people using custom_updater

**Comment by nervetattoo** [comment]
Thanks for all the debugging guys! I merged #16 and will be updating tracker.json as well @essell ;)
There is still one dependency from unpkg for `Debouncer` so it should still cause issues, but one less network request is always great nevertheless.

**Comment by nervetattoo** [comment]
I'm also planning to refactor the card to bundle its dependencies (except LitElement) because I hate how a lot of custom cards doesn't work without internet, so this will become a solved problem

**Comment by Diondk** [comment]
My custom card stopped working yesterday evening, did you updated already?

**Comment by essell** [comment]
Appreciate all the help and really believe this is the best thermostat card in the game for Lovelace.

Here's a funny story--I actually didn't mind loading the JS externally. I have a remote home (okay a mobile home) that I'm monitoring that's located in an area without good internet access. I have a mobile hotspot there, wired to a signal booster and Yagi antenna on the roof. It's on a grandfathered cheap 2GB every 60 days plan which is slowly being eaten up when I access HASS, one tiny bundled javascript library at a time. :)

**Comment by nervetattoo** [comment]
So for your use case using unpkg is actually a net-win as you theoretically could have libs in the cache from other sites @essell 😄 I'm guessing hard on most people actually using HA from the same network as the HA instance though; At least thats my case, almost entirely using it locally only.

**Comment by treb42** [comment]
with the current version I went from the the red box of 
`Custom element doesn't exist: simple-thermostat`
to 
`Uncaught (in promise) TypeError: html is not a function`

![image](https://user-images.githubusercontent.com/25442387/51206307-0d97dd80-1908-11e9-9c69-f394972e9fb4.png)

**Comment by thomasloven** [comment]
Home Assistant version less than 0.84, @treb42?

**Comment by treb42** [comment]
> Home Assistant version less than 0.84, @treb42?

Yes, still on 0.83.3...guess I'll read the release notes and update tomorrow

**Comment by treb42** [comment]
Updated to 0.85.1 and everything is looking fine again. 
Thanks for the tip @thomasloven

**Comment by Cludch** [comment]
I am still experiencing this issue on 0.85.1 and already updated to 0.12.1

**Comment by Diondk** [comment]
I am also still experiencing this issue on 0.85.1 and updated to 0.12.1.

**Comment by Cludch** [comment]
Already tried that as well. Did a hard refresh and cleared my cache

**Comment by nervetattoo** [comment]
Do you see any errors in your browsers console under dev tools @Cludch ? Also, what browser+version are you running?

**Comment by Cludch** [comment]
![Errors](https://user-images.githubusercontent.com/5933107/51345320-ef161b80-1a9a-11e9-8c25-ad2b196f95d7.PNG)
What seems strange to me is that Home-Assistant tries to load from localhost even though there is a reverse proxy in between.

I am using the latest Chrome version on Windows.

**Comment by detxm80** [comment]
same issue here

**Comment by nervetattoo** [comment]
That is strange @Cludch @detxm80 , since this card no longer pulls in lit-element.js from unpkg this means that you either don't have an updated version or its browser cached.

The import from localhost have to be a bug in the unpkg-published lit-element, I noticed it in the published source a few days ago as well.

**Comment by bhaap** [comment]
It is important that after you change the simple-thermostat.js file that you in your lovelace configuration file change the version of the include. otherwise lovelace will used the cached old version of the js file. what number you put in does not matter if you are doing this manually.

So for example:

```yaml
resources:
  - url: /local/simple-thermostat/simple-thermostat.js?v=1
    type: module
```

becomes

```yaml
resources:
  - url: /local/simple-thermostat/simple-thermostat.js?v=1.1
    type: module
```
Im using this exact github js file just cloned in the newest version of home assistant and it is working flawless on Safari, Chrome, Opera, Firefox and the Home assistant iOS-app
