### ISSUE TITLE
Allow support for water heater via control section (modes)

### ISSUE THREAD

**Issue by fireheadman** [nervetattoo/simple-thermostat#167]
I see that the 'control' section allows for HVAC, Presets, Fan, and Swing
would it be possible to include modes for water heaters?  Unsure if it would be name 'operations_list' ?

Example (Rheem EcoNet water heater)
<img width="333" alt="image" src="https://user-images.githubusercontent.com/19847195/97528991-99131f00-1974-11eb-903d-5082f65a47f5.png">

and here is a HVAC system (Rheem EcoNet furnace)
<img width="341" alt="image" src="https://user-images.githubusercontent.com/19847195/97529052-b7791a80-1974-11eb-92f0-de868bf2ee2d.png">

**Comment by fireheadman** [comment]
Per the screenshots and the usage of 'controls' in simple-thermostat, is hvac the same as hvac_modes  AND  fan the same as fan_modes (from the attributes of an entity)?

so 'operation_list' would become 'operation' ? Or does the '_list' mess this up?

**Comment by mstarks01** [comment]
Hey @fireheadman your card looks great. Unfortunately, I've run into issues integrating it. Is this a button card? I've tried custom, entity, entities and button cards, but i'm doing something wrong when trying to work your config in. Of course I've changed the entity ID as well. Can you please post the entire YAML?

**Comment by fireheadman** [comment]
```
type: custom:vertical-stack-in-card
cards:
  - type: custom:simple-thermostat
    entity: water_heater.hydra
    step_size: 1
    header: false
    //header: null
    //  name: ''
    //  icon: mdi:thermometer
    decimals: 0
    service:
      domain: water_heater
      service: set_temperature
    hide:
      temperature: true
    sensors:
      - entity: water_heater.hydra
        name: Current Mode
        attribute: operation_mode
      - entity: water_heater.hydra
        name: Water Temp Setpoint
        attribute: temperature
      - entity: sensor.hydra_power_usage_today
        name: Energy Used (kWh)
        //attribute: power_usage_today
      - entity: sensor.hydra_tank_health
        name: Tank Health (%)
        //attribute: tank_health
      - entity: sensor.hydra_compressor_health
        name: Compressor Health (%)
        //attribute: hot_water_availability
  - type: divider
  - type: horizontal-stack
    cards:
      - type: button
        icon: mdi:leaf
        icon_height: 20px
        name: Eco
        tap_action:
          action: call-service
          service: water_heater.set_operation_mode
          service_data:
            entity_id: water_heater.hydra
            operation_mode: eco
      - type: button
        icon: mdi:radiator
        icon_height: 20px
        name: Heat Pump
        tap_action:
          action: call-service
          service: water_heater.set_operation_mode
          service_data:
            entity_id: water_heater.hydra
            operation_mode: heat_pump
      - type: button
        icon: mdi:thermometer-lines
        icon_height: 20px
        name: High Demand
        tap_action:
          action: call-service
          service: water_heater.set_operation_mode
          service_data:
            entity_id: water_heater.hydra
            operation_mode: high_demand
      - type: button
        icon: mdi:flash-outline
        icon_height: 20px
        name: Electric
        tap_action:
          action: call-service
          service: water_heater.set_operation_mode
          service_data:
            entity_id: water_heater.hydra
            operation_mode: electric
      - type: button
        icon: mdi:stop-circle-outline
        icon_height: 20px
        name: 'Off'
        tap_action:
          action: call-service
          service: water_heater.set_operation_mode
          service_data:
            entity_id: water_heater.hydra
            operation_mode: 'off'
  - type: divider
  - type: horizontal-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.hydra_power_usage_today
            name: Energy Used
            color: orange
        show:
          icon_adaptive_color: true
          extrema: true
        hours_to_show: 48
        points_per_hour: 1
        animate: true
        //height: 150
        //lower_bound: 0
        //upper_bound: 8
        unit: kWh
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.hydra_available_hot_water
            name: Hot Water Availability
            color: red
        show:
          icon_adaptive_color: true
          extrema: true
        hours_to_show: 48
        points_per_hour: 1
        animate: true
        //height: 150
        //lower_bound: 0
        //upper_bound: 120
        unit: '%'

```

**Comment by fireheadman** [comment]
that give this...
<img width="357" alt="image" src="https://user-images.githubusercontent.com/19847195/174524798-1be671d5-0b9f-429c-865a-9e068e70e5d3.png">

**Comment by mstarks01** [comment]
Outstanding. Almost there. You have a few sensors I don't have; namely, tank health, compressor health and total hot water availability. Are those perhaps because of a different model or did you do something custom with a template sensor?

**Comment by fireheadman** [comment]
forgot about those 2 sensors....
These are templates

rheem_hvac_humidity.yaml               
```
---
#
#
#

- sensor:
  - name: "Rheem: HVAC Humidity"
#    icon: mdi:water-percent
    device_class: humidity
    state_class: measurement
    state: "{{ state_attr('climate.dragon', 'current_humidity') }}"
```

rheem_hvac_temperature.yaml
```
---
#
#
#

- sensor:
  - name: "Rheem: HVAC Temperature"
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°F"
    state: "{{ state_attr('climate.dragon', 'current_temperature') }}"
```
