### ISSUE TITLE
-/+ toggle in card not responding, does when settings are pulled up

### ISSUE THREAD

**Issue by fireheadman** [nervetattoo/simple-thermostat#168]
This will not change the setting... instead I get a WARNING message:
2020-10-29 15:29:53 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities water_heater.hydra

![image](https://user-images.githubusercontent.com/19847195/97634721-d078de80-19fb-11eb-87e8-04c9414a1b04.png)

But if I go into the card settings by clicking on the name/title, this will change the temperature
![image](https://user-images.githubusercontent.com/19847195/97634764-e38bae80-19fb-11eb-8cba-fc7ca80329dd.png)

**Comment by fireheadman** [comment]
odd part is... the entity is valid, just something with trying to adjust the temp is not working as expected.

![image](https://user-images.githubusercontent.com/19847195/97635004-454c1880-19fc-11eb-9c7e-a1d562788869.png)

![image](https://user-images.githubusercontent.com/19847195/97635048-5563f800-19fc-11eb-8fbf-14d3d56aff46.png)

**Comment by nervetattoo** [comment]
I guess water_heater is a different domain so requires different service call. Happy to review a PR that adds support for water heaters

**Comment by fireheadman** [comment]
I"m not a person that would know how to do a PR.
I'm just an end user that is asking for the functionality.
sorry about that.

definitely very willing to help in testing new code in anyway possible.

**Comment by fireheadman** [comment]
how is a PR created?

**Comment by nervetattoo** [comment]
https://guides.github.com/activities/hello-world/

**Comment by fireheadman** [comment]
hmmm... seems a bit over my head, so hopefully someone that understands
your code can chip in to make your integration work with water heaters as
you mentioned.

**Comment by ntalekt** [comment]
Same result in HA 2022.5.4 with the v2.4.3 card. The water_heater entities are my pool and spa from the [Pentair Intellicenter](https://github.com/jlvaillant/intellicenter) custom integration.

I'm seeing the following services:
- water_heater.set_away_mode
- water_heater.set_operation_mode
- water_heater.set_temperature
- water_heater.turn_off
- water_heater.turn_on

**Comment by robpneu** [comment]
Try adding the following to the configuration:

```
service:
  domain: water_heater
  service: set_temperature
```

**Comment by fireheadman** [comment]
@robpneu 
Your awesome!!!!... thanks a million for those 2 lines of code.  works beautifully now!

For those curious, this is my card info:
I also use the scheduler to step up the water heater on the weekends for a couple/few hrs so we can all have hot water.....
![image](https://user-images.githubusercontent.com/19847195/173282803-7cf926e1-344f-4ae1-ba68-629dbebe7214.png)



Card:
```
type: custom:vertical-stack-in-card
cards:
  - type: custom:simple-thermostat
    entity: water_heater.hydra
    step_size: 1
    header: false
    //header: null
    //  name: ''
    //  icon: mdi:thermometer
    decimals: 0
    service:
      domain: water_heater
      service: set_temperature
    hide:
      temperature: true
    sensors:
      - entity: water_heater.hydra
        name: Current Mode
        attribute: operation_mode
      - entity: water_heater.hydra
        name: Water Temp Setpoint
        attribute: temperature
      - entity: sensor.hydra_power_usage_today
        name: Energy Used (kWh)
        //attribute: power_usage_today
      - entity: sensor.hydra_tank_health
        name: Tank Health (%)
        //attribute: tank_health
      - entity: sensor.hydra_compressor_health
        name: Compressor Health (%)
        //attribute: hot_water_availability
  - type: divider
  - type: horizontal-stack
    cards:
      - type: button
        icon: mdi:leaf
        icon_height: 20px
        name: Eco
        tap_action:
          action: call-service
          service: water_heater.set_operation_mode
          service_data:
            entity_id: water_heater.hydra
            operation_mode: eco
      - type: button
        icon: mdi:radiator
        icon_height: 20px
        name: Heat Pump
        tap_action:
          action: call-service
          service: water_heater.set_operation_mode
          service_data:
            entity_id: water_heater.hydra
            operation_mode: heat_pump
      - type: button
        icon: mdi:thermometer-lines
        icon_height: 20px
        name: High Demand
        tap_action:
          action: call-service
          service: water_heater.set_operation_mode
          service_data:
            entity_id: water_heater.hydra
            operation_mode: high_demand
      - type: button
        icon: mdi:flash-outline
        icon_height: 20px
        name: Electric
        tap_action:
          action: call-service
          service: water_heater.set_operation_mode
          service_data:
            entity_id: water_heater.hydra
            operation_mode: electric
      - type: button
```
