### ISSUE TITLE
Add label for toggle_entity

### ISSUE THREAD

**Issue by flyboy013** [nervetattoo/simple-thermostat#172]
I have found a use for the toggle_entity capability, but I see that there is no label associated with the switch.   Is it possible to add a label (or take it from entity) such that the label would display next to the switch?  As it is, there's no knowing what the switch is for.

**Comment by nervetattoo** [comment]
Pinging @clau-bucur who submitted the PR for that support

**Comment by clau-bucur** [comment]
Will look into it soon.

**Comment by flyboy013** [comment]
@clau-bucur  here is my use case and thoughts.

I have multiple HVAC systems in my motorhome and I can enable the Automatic Generator Start (AGS) feature on each system such that if I'm not plugged into a power source, the system will automatically start the generator in order to power the HVAC system.  This is useful if a pet is left in the motorhome and the temperature change requires the unit to be turned on.

I had thought of adding on/off buttons in a card just below each thermostat, but having the toggle entity provides a great way of keeping it all together.  My thought is to have the label to the left of the toggle as shown below.

![climate](https://user-images.githubusercontent.com/44688061/98976399-4e051a00-24e5-11eb-8a98-ad08c9a6859d.png)

**Comment by clau-bucur** [comment]
@flyboy013 I understand. I'm using the toggle for a pretty similar use-case.
Proposed solution:
```
toggle_entity:
  entity_id: entity
  name: true|string - true will defaut to the entity name, or you can override it with your string of choice.
                      if name not set, it will not show any text near the toggle.
```
