### ISSUE TITLE
Display modes in the order configured

### ISSUE THREAD

**Issue by DeltaAngle** [nervetattoo/simple-thermostat#185]
Modes are not displayed in the order they are configured. 

For example, this is a subset of the card configuration for the 'Fan' control.
```
fan:
    _name: Fan‌
    auto:
      icon: false
    diffuse:
      name: quiet
    low:
      name: 1
    medium:
      name: 2
    middle:
      name: 3
    high:
      name: 4
```
'Quiet' mode is after 'auto', and I've renamed four of the modes as numerical values, in numerical order. But, the card renders like this, 
![image](https://user-images.githubusercontent.com/16471863/100908059-e7d63c00-347f-11eb-98f3-21e62e1a3307.png)

The numbers are out of order and 'quiet' mode is displayed a the end of the list.
