### ISSUE TITLE
How to remove the inscription "operation"?

### ISSUE THREAD

**Issue by sashadeg** [nervetattoo/simple-thermostat#193]
I just can't find a solution to this problem.
Found this option but it doesn't work. How to use it correctly?
 ```yaml
 control:
   _names: false
 ```
My config:
 ```yaml
       - type: custom:simple-thermostat
          entity: climate.konditsioner
          name: false
          step_size: 1
          step_layout: row
          hide: 
            temperature: true
            state: true
          style: |
            ha-card {
              --st-font-size-xl: 30px; #регулировка температуры
              --st-font-size-m: 20px;
              --st-font-size-title: 20px; #заголовок
              --st-font-size-sensors: 30px;
              --st-spacing: 4px;
            }
          control:
            hvac:
              "off":
                name: false
              "auto":
                name: false
                icon: mdi:autorenew
              "cool":
                name: false
                icon: mdi:snowflake
              "heat":
                name: false
                icon: mdi:fire
              "dry":
                name: false
                icon: mdi:water-percent
              "fan_only":
                name: false
                icon: mdi:fan
 ```
![thermostat-card](https://user-images.githubusercontent.com/63294695/101483681-57659300-397a-11eb-9960-db4dd0420f1f.png)
![2020-12-08_17-06-32](https://user-images.githubusercontent.com/63294695/101483688-59c7ed00-397a-11eb-97a5-cfd157d458ae.png)

**Comment by tomvanswam** [comment]
Add `_headings: false` under `control`

**Comment by sashadeg** [comment]
> Add `_headings: false` under `control`

Thanks! 
Спасибо!

**Comment by nickrout** [comment]
Sorry to revive an old issue, but this isn't working for me.

Config:
```
type: 'custom:simple-thermostat'
entity: climate.kitchen
show_header: false
decimals: '0'
step_size: '1'
control:
  _headers: false
  hvac: true
```

**Comment by cklam2** [comment]
Seems that the behavior changed in 2.x and _headings doesn't work anymore.
Could kind of hide it by setting the _name to **single** space. Not the ideal solution in my opinion.
```
control:
  hvac:
    _name: ' '
    'off':
      name: 'Off'
    heat:
      name: 'On'
  preset:
    _name: ' '
    none:
      name: Normal
```
