### ISSUE TITLE
Support presets for quickly setting some predefined desired temperatures + modes

### ISSUE THREAD

**Issue by nervetattoo** [nervetattoo/simple-thermostat#2]
Personally I often use a few specific temperatures that are normally handled by automations, say 23℃ in daytime and 16℃ at night. Having these as presets with buttons would make it easier to manually trigger such temperatures and would also be an easier way for people who haven't figured out automations.

It would also be great for things like heat pumps / AC where you can have both a heat and cool mode.

Config:

```yaml
presets:
  - name: Daytime
     temperature: 23
     mode: heat
  - name: Night
     temperature: 16
  - name: Hot summer
     temperature: 20
     mode: cool
```

**Comment by Klagio** [comment]
I would add also the AWAY mode

**Comment by jsblake** [comment]
I'm not against some preset temperature buttons, but maybe that would be better done with a separate button card. But, I am definitely with @Klagio it would be very useful to have buttons to switch modes vs. just a drop down

**Comment by banolka** [comment]
Will it be possible to implement this or allow to add custom scripts trigers like puttons to triger scripts like this:
```

'pranie_off':
  alias: Pranie OFF
  sequence:
  - data:
      entity_id: climate.man_cave
      temperature: 17
    service: climate.set_temperature
```
