### ISSUE TITLE
Custom Updater not working with the latest release

### ISSUE THREAD

**Issue by arigit** [nervetattoo/simple-thermostat#20]
I have custom_updater up and running, showing various cards and components.
I manually installed  simple-thermostat, added the card and it displays with not issue.

However, custom-updater does NOT list the card at all. Tried restarting HA, reloading the UI, forcing custom_update to re-check etc.

```
custom_updater:
  track:
    - cards
    - components
  card_urls:
    - https://raw.githubusercontent.com/nervetattoo/simple-thermostat/master/tracker.json
```

ui-lovelace.yaml

```
resources:
  - url: /local/vertical-stack-in-card.js?v=v0.1.0
    type: js    
  - url: /local/tracker-card.js?v=0.1.5
    type: js
  - url: /local/simple-thermostat.min.js?v=0
    type: module

```

![image](https://user-images.githubusercontent.com/652673/51804085-3aae8f00-222a-11e9-974a-ff83633cb6b2.png)

**Comment by nervetattoo** [comment]
How weird. I just checked and I get a listed change. Do you see any errors in the HA log from the custom_updater?

**Comment by arigit** [comment]
I captured a debug log. Custom updater doesn't seem to see your card for some reason

Posted the log here.

https://paste.ubuntu.com/p/qRf4KRFMbp/

In the second line I can see the custom_updater picked up your repo.

In the third line, I can see it downloaded your repo content and added to it's 'database' the version and link to the latest simple-thermostat:

'simple-thermostat': ['simple-thermostat', '0.14.0', 'https://github.com/nervetattoo/simple-thermostat/releases/download/0.14.0/simple-thermostat.min.js'

But finally in the last line, I can see that custom_updater did NOT find the local installation of your custom card.

2019-01-30 01:24:30 DEBUG (Thread-8) [pyupdate.ha_custom.custom_cards] get_sensor_data: [{'has_update': [], 'vertical-stack-in-card': {'has_update': False, 'local': 'v0.1.0', 'change_log': 'https://github.com/custom-cards/vertical-stack-in-card', 'remote': 'v0.1.0', 'not_local': False, 'repo': 'https://github.com/custom-cards/vertical-stack-in-card'}, 'tracker-card': {'has_update': False, 'local': '0.2.0', 'change_log': 'https://github.com/custom-cards/tracker-card', 'remote': '0.2.0', 'not_local': False, 'repo': 'https://github.com/custom-cards/tracker-card'}, 'domain': 'custom_cards'}, 0]

However your card is installed:
```
~/.homeassistant/www$ ls
simple-thermostat.min.js  tracker-card.js  vertical-stack-in-card.js
```
```

title: Home Dashboard

resources:
  - url: /local/vertical-stack-in-card.js?v=v0.1.0
    type: js
  - url: /local/tracker-card.js?v=0.2.0
    type: js
  - url: /local/simple-thermostat.min.js?v=0.0.1
    type: module

views:

```
and it works:

![image](https://user-images.githubusercontent.com/652673/51962870-94cc7180-242f-11e9-99a4-85e4f4247735.png)


So custom_updater is no setting up a sensor for your card:


```
sensor.custom_card_tracker | 0 | has_update:  vertical-stack-in-card: {   "has_update": false,   "local": "v0.1.0",   "change_log": "https://github.com/custom-cards/vertical-stack-in-card",   "remote": "v0.1.0",   "not_local": false,   "repo": "https://github.com/custom-cards/vertical-stack-in-card" } tracker-card: {   "has_update": false,   "local": "0.2.0",   "change_log": "https://github.com/custom-cards/tracker-card",   "remote": "0.2.0",   "not_local": false,   "repo": "https://github.com/custom-cards/tracker-card" } domain: custom_cards hidden: false
-- | -- | --

```

Any idea of what could be wrong?
