### ISSUE TITLE
Support for Mill devices

### ISSUE THREAD

**Issue by magnusoverli** [nervetattoo/simple-thermostat#211]
Hi!

Mill devices uses their own service calls, so we cannot use `climate.set_temperature` or similar.
The Mill integration uses the service call: mill.set_room_temperature and has the following attributes:

Service data attribute | Optional | Description
-- | -- | --
room_name | no | String with room name.
away_temp | yes | Integer with temperature
comfort_temp | yes | Integer with temperature
sleep_temp | yes | Integer with temperature

Can support for this be added to Simple Thermostat?

**Comment by nervetattoo** [comment]
From 2.0 I _think_ this should work with the new configuration options:

```yaml
entity: mill.my_mill
service:
  domain: mill
  service: set_room_temperature
  data:
    room_name: my_room
setpoints:
  comfort_temp:
```

You can include all three setpoints, but the UI is never tested with 3 setpoints so far.
