### ISSUE TITLE
Hide presets and text

### ISSUE THREAD

**Issue by B3voholic** [nervetattoo/simple-thermostat#218]
There is not a way to hide both the preset section and the labels for the buttons.  Is this possible?

**Comment by nervetattoo** [comment]
So hide presets and hvac action button labels, but keeping the hvac buttons with icons only?
Sounds like something like:

```yaml
control:
  hvac:
    some_mode:
      name: false
     ...
```

Yes it means repeating every mode in the config, and its not elegant. 
Breaking changes to the config format are coming so I will do a hard consideration on completely rewriting the current control field to support more of the requests I've seen over the years.

**Comment by nervetattoo** [comment]
As of 2.0 this can be achieved easily:
```yaml
layout:
  mode:
    names: false
    headings: false
```
