### ISSUE TITLE
Blacklist or whitelist for modes

### ISSUE THREAD

**Issue by nils-z** [nervetattoo/simple-thermostat#23]
My zwave thermostats have 5 modes but I need only heat and off. The three unused buttons take up a lot of space in the UI:
It would be nice to have an option for hiding modes.

![image](https://user-images.githubusercontent.com/5261221/52536490-89e0dd80-2d5b-11e9-8aed-fc2982039262.png)

**Comment by nervetattoo** [comment]
Yeah; I can see how this is very cluttering.
I almost should get myself a more complex thermostat component just to see these cases for myself!

Adding an option is simple enough so I guess I'll be adding one of these flavours for configuration. 

```yaml
hide:
  mode:
    - heat_eco
    - manufacturer_specific

hide:
  mode: false
mode:
  include:
    - on
    - off
```

**Comment by fredrike** [comment]
Perhaps the icon mode could be added to the configuration:

```yaml
mode:
  - type: on
    icon: mdi:on
```

**Comment by KarimGeiger** [comment]
I'd really appreciate both of these features. If I could get rid of the "an" mode and add an icon to the "boost" mode, it would be absolutely fantastic!

<img width="466" alt="screenshot 2019-02-26 at 15 18 02" src="https://user-images.githubusercontent.com/2329930/53419248-cb1ef180-39d9-11e9-9cef-13021bed77c7.png">

By the way, thanks for the awesome work so far, and also thanks for keeping it up with the development and adding new features. The change from dropdown to buttons looks great 👍

**Comment by nervetattoo** [comment]
This will happen folks, just be patient as I find the time 🗓

**Comment by nervetattoo** [comment]
Thinking through this a little bit more my current intention is to go with the following approach, I'm sharing it first to hear if people think this makes sense.
I will deprecate the `hide.mode` and instead introduce the `modes` top level key. `modes` will be merged with the entity reported modes by default, meaning you can override items there, but you need to explicitly configure each item you want to change, or else it will use the defaults and look like today.  I'm on the fence about also allowing to specify it to not merge, mostly because its hard to find a succinct config structure while supporting that in a good way.
Without disabling merging, the only use case that becomes hard is if you want to _only include these two sensors out of 7 reported ones_

Anyway, here's the planned config:

```yaml
modes:
  weird_mode: false
  off:
    name: Make it cold
    icon: mdi:whitewalker
  on:
    name: On
    icon: false
    color: <any valid css color>
  wonky_mode:
    include: false
```

It also supports the shorthand from `hide.mode`:
```yaml
modes: true|false
```

If I decide to allow disabling merging I'm leaning towards a special key in the modes map:
```yaml
modes:
  _merge: false
  off: true
  on: true
```

Are there anything you feel is not supported with this? I think it covers all requests and feedback I've heard quite extensively, but just to be sure I want to let this sit here for a day or two before I implement the changes.
