### ISSUE TITLE
Control _names fails and mode _name no longer accepts bool false

### ISSUE THREAD

**Issue by kylehase** [nervetattoo/simple-thermostat#231]
Found in 2.0.0 and 2.0.1

Setting control: _names to false, per the documentation, no longer works. UI has no change.
```yaml
cards:
  - type: 'custom:simple-thermostat'
    control:
      _names: false
```

Additionally, setting the individual mode _name: to bool false results in the default string "Operation". Setting _name: to strings works as intended.
```yaml
cards:
  - type: 'custom:simple-thermostat'
    control:
      hvac:
        _name: false
```

I see this [recent commit](https://github.com/nervetattoo/simple-thermostat/commit/e388d2109e0a6e9693de3abe095ef00383e8ddb2), which appears related, but currently lack the understanding to know if it fixes this.

**Comment by Larx** [comment]
I don't know if that's related: I don't find any working option to remove the headings for e.g. the modes- and preset-row. The old version (_headings: false) does not work. As I understand it, this is now supposed to be handled by the "layout/mode/headings" block, but this doesn't work for me.

**Comment by kylehase** [comment]
@Larx Thanks for the pointer. Your comment made me try the following, which worked for me.

```yaml
    layout:
      mode:
        headings: false
```
