### ISSUE TITLE
Reduce temperature not working

### ISSUE THREAD

**Issue by nickdos** [nervetattoo/simple-thermostat#240]
Using compact mode where the temperature actions are `-` and `+`, increasing the temperature works as expected but reducing the temperature does not work - temp stays the same. I have `decimals: 0`. 

Using the normal climate controls works as expected, so issue is with this plugin.

**Comment by nervetattoo** [comment]
Make sure to clear your browser cache.
Also, always paste your config and preferably a screenshot.
If you can open your browsers devtools console before triggering the bug, and then look for any errors (red text) there it will be helpful.

To be clear; Reducing temperature works just fine for a lot of other people, myself included so it needs more details on what might be causing the issue in your setup.

**Comment by nickdos** [comment]
Tried multiple browsers and clearing cache and still see this error.

Here's my config:

```yaml
control:
  _headings: false
  fan: true
  hvac:
    dry: false
    fan_only:
      name: fan
    heat_cool:
      name: auto
decimals: 0
entity: climate.daikin_ac
hide:
  temperature: true
  state: true
sensors:
  - entity: sensor.dining_room_esp_temperature
    name: Dining
  - entity: sensor.living_room_temperature
    name: Living
type: 'custom:simple-thermostat'
layout:
  mode:
    headings: false
  step: row
```

No JS errors or warnings in console either.

Behaviour I see is:
- increase -> click `+` and temperature value goes from black text 20° to red text 21° and then a second or two later, changes back to black text as 21°.
- decrease -> click `-` and temperature values stays the same (20°) but font colour changes black to red. Then a few seconds later changes back to black colour.
