### ISSUE TITLE
Control icons gone

### ISSUE THREAD

**Issue by hmmbob** [nervetattoo/simple-thermostat#244]
I've been using your card quite a long time, but recent changes made my "control button icons" disappear and I can't get them back.... What am I doing wrong? Code used:

```yaml
      - type: "custom:simple-thermostat"
        card_mod:
          style: |
            ha-card {
            margin: 0px 14px -5px 14px;
            --st-font-size-title: 18px;
            --st-font-size-xl: 
            }
        entity: climate.woonkamer
        header: false
        label:
          temperature: Temperatuur
        hide:
          state: true
        control:
          preset:
            sleep:
              icon: mdi:sleep
            away:
              icon: mdi:leaf
            comfort:
              icon: mdi:fire
            home:
              icon: mdi:home-thermometer
            eco:
              icon: mdi:thermometer-off
        sensors:
          - entity: sensor.bme280_temperature
            name: Buiten
          - attribute: modulation_level
            name: Brander
            unit: "%"
```
Screenshot before:
![image](https://user-images.githubusercontent.com/33529490/114298169-59209e00-9ab5-11eb-8be5-8f785a437d1a.png)

Screenshot now:
![image](https://user-images.githubusercontent.com/33529490/114298226-a43ab100-9ab5-11eb-99d9-a61336dea4c8.png)

(the question is only about the bottom row: I'd like to hide the text "voorinstelling" (preset) and get back the icons, together with the labels)

**Comment by nervetattoo** [comment]
Can you share your entities attributes as well?
Also make sure you clear browser cache and retry.

To hide the headings for controls do
```yaml
layout:
  mode:
    headings: false
```
