### ISSUE TITLE
Can't get sensors to display

### ISSUE THREAD

**Issue by julianrinaldi** [nervetattoo/simple-thermostat#254]
**Describe the bug**
Sensors added in the configuration don't show up in the frontend

**To Reproduce**
Add a sensor to the configuration

**Expected behavior**
I would expect the sensor entity to be displayed

```yaml
- type: 'custom:simple-thermostat'
    entity: climate.ecobee4_thermostat
    step_size: '1'
    sensors:
      - entity: sensor.sense_hvac_usage
        name: Power
    control:
      hvac:
        cool:
          name: Cool
        heat:
          name: Heat
        heat_cool:
          name: Auto
        'off':
          name: 'Off'
    decimals: '0'
    fallback: 'OFF'
    layout:
      step: row
      sensors: list
      mode:
        headings: false
        icons: true
```

**Screenshots**
![CleanShot 2021-05-03 at 14 46 22](https://user-images.githubusercontent.com/492435/116918918-8bd63600-ac1e-11eb-89ca-c1676d3799c9.png)

**Browser**
 - OS: Mac
 - Browser: Brave
 - Simple Thermostat version from browser console: v2.4.0
 - Home Assistant version: core-2021.5.0b4
--
