### ISSUE TITLE
mode-title hiding

### ISSUE THREAD

**Issue by rengaboy** [nervetattoo/simple-thermostat#255]
Is it possible to get an configuration option to hide mode-title?

**Comment by nervetattoo** [comment]
It already exists

```yaml
layout:
  mode:
    names: false
```
