### ISSUE TITLE
Bug? View that includes simple-thermostat card using missing entity remains blanc

### ISSUE THREAD

**Issue by RoboMagus** [nervetattoo/simple-thermostat#262]
**Describe the bug**
I found this minor inconvenience when re-defining my airconditioner in ESPHome which was also used in the simple-thermostat card. When the entity which the simple-thermostat card refers to does not exist, the entire dashboard view remains unpopulated.
This behavior is accompanied by the following error in home assistant logging:
```
2021-06-22 21:45:16 ERROR (MainThread) [frontend.js.latest.202106030] https://[REDACTED]/hacsfiles/simple-thermostat/simple-thermostat.js:285:19980 Uncaught TypeError: Cannot read property 'attributes' of undefined
```

**To Reproduce**
Remove the entity for which the thermostat card is configured from home assistant.

**Expected behavior**
I expect the card not showing up, showing an error, or otherwise not completely taking down the lovelace dashboard.

```yaml
    - type: custom:simple-thermostat
      entity: climate.mhi_ac_ctrl
      header:
        name: Slaapkamer Airco
      step_size: 1
      decimals: 1
      layout:
        mode:
          names: false
          icons: true
          headings: false
      version: 3
      control:
        hvac:
          heat_cool: false
```

**Browser**
Reproduces in the android home assistant app, as well as on chrome / firefox browsers on both desktop and phone (android).
 - Simple Thermostat version from browser console:  simple-thermostat: 2.4.2
 - Home Assistant version: 2021.6.6

__quick fix:__
As a quick workaround untill I got my entities sorted out again I wrapped the simple-thermostat card with a conditional card as follows:
```yaml
    - type: conditional
      conditions:
        - entity: climate.mhi_ac_ctrl
          state_not: "unknown"
      card:
        type: custom:simple-thermostat
        [...]
```
This avoids the JS error and will thus cause the rest of the view to load as expected
