### ISSUE TITLE
Can't set temp with hidden setpoint

### ISSUE THREAD

**Issue by bkaufx** [nervetattoo/simple-thermostat#265]
**Describe the bug**
Hiding a setpoint in the card causes a dual point thermostat to be treated like a single point thermostat.  The set_temperature service is called with a single temperature instead of separate target_temp_low and target_temp_high arguments.  However, [Home Assistant requires both target_temp_low and target_temp_high](https://www.home-assistant.io/integrations/climate/#service-climateset_temperature).

**To Reproduce**
1. Have dual setpoint thermostat
2. Hide one of the setpoints in the card
3. Try to adjust target temp
4. See error "Failed to call service climate/set_temperature. some but not all values in the same group of inclusion 'temperature' @ data[<temperature>]"

**Expected behavior**
Even if one of the setpoints is hidden, set_temperature should still be called with both target_temp_high and target_temp_low.

```yaml
      - type: custom:simple-thermostat
        entity: climate.thermostat
        setpoints:
          target_temp_low:
            hide: true
          target_temp_high:
```

**Screenshots**
![image](https://user-images.githubusercontent.com/31808830/126078301-40e379b2-5bce-4211-86db-c6549578fa54.png)

**Browser**
 - OS: Windows 10
 - Browser: Edge & Firefox
 - Simple Thermostat version from browser console: 2.4.2 (according to HACS and also found in .js file)
 - Home Assistant version: 2021.7.3
