### ISSUE TITLE
Operation mode

### ISSUE THREAD

**Issue by loop2** [nervetattoo/simple-thermostat#269]
**Describe the bug**
On operation mode of my Tado climate i have to option with the same icon; one with "AUTO" and one with "HEAT/COOL" where is the difference of this modes?

In addition where i can change the italian traslations of operation buttons? 
Thanks!

![Immagine 2021-08-19 095858](https://user-images.githubusercontent.com/32266997/130030769-f1eccc0b-360f-4bd2-b18e-32a95d720f5f.jpg)

**Comment by loop2** [comment]
nobody know how change the translations?

**Comment by loop2** [comment]
Ok, i have used this instructions to remove a mode e rename the fan_only:
```

   control:
      hvac:
        some_mode: false
        another_mode: false
        'off':
          name: Make it cold
          icon: false
        'on':
          name: false
          icon: mdi:whitewalker
```
