### ISSUE TITLE
Configuration card

### ISSUE THREAD

**Issue by pepsonEL** [nervetattoo/simple-thermostat#273]
Hi. I se you card to setup my boiler thermostat. But it show no comfotable view.  Some text is cutting. Is any chance to change this , small size or add only icon for it ?
![thermostat](https://user-images.githubusercontent.com/71824185/133985542-1298381e-3fc7-4a03-b551-a7e67f760cb9.jpg)

**Comment by ayonix** [comment]
You should be able to, as an example:
```yaml
control:
  preset:
    komfort:
      name: false
      icon: 'mdi:weather-sunny'
```
