### ISSUE TITLE
Header Toggle is not showing real state / Action is not executed

### ISSUE THREAD

**Issue by ed-holland** [nervetattoo/simple-thermostat#276]
**Describe the bug**
I'm using a header toggle with a lock entity (provided by a tuya TH213 device).
The action to enable the lock, does not lock.
If i lock using the lock-entity, it does not show the status

**To Reproduce**
1. Click on Toggle to change state
2. Lock entity does not change
3. Use entity to lock
4. Toggle does not change

**Expected behavior**
Toggle to follow lock status

```yaml
type: custom:simple-thermostat
entity: climate.og_bath_parents
step_size: '1'
decimals: '0'
control:
  preset:
    Home: true
    Smart: false
    Sleep: true
    Away: true
  hvac:
    heat:
      name: false
    off:
      name: false
sensors:
  - attribute: external_temperature
    name: Floor
    unit: °C
    decimals: 1
  - attribute: heating_switch_state
    name: Heating
  - entity: lock.og_bath_parents
    name: Locked
header:
  toggle:
    entity: lock.og_bath_parents
    name: Lock
layout:
  mode:
    names: true
    icons: true
    headings: false
hide:
  state: true
```

**Screenshots**
![image](https://user-images.githubusercontent.com/53995991/134798645-8abf6d8f-dbc1-4b50-9f82-b60ef6e15433.png)

**Browser**
 - OS: Windos
 - Browser: Chrome
 - Simple Thermostat version from browser console: latest
 - Home Assistant version: 2021.9.7

**Comment by DenisBY** [comment]
I have the same issue

**Comment by Strixx76** [comment]
I have Tuya TS0601 thermostats and I would also like to able to switch the child lock on and off.
Maybe the best way to solve it would be to have a choice to add an lock-entity instead of an toggle/switch in the header?

**Comment by alienatedsec** [comment]
It sounds like a great idea - I have the same which seems to be annoying as cannot be enabled.

![image](https://user-images.githubusercontent.com/73167064/214519792-66464a9f-4585-4327-9521-3b994dc93312.png)

@ed-holland I would not call it a bug but an enhancement to define what a toggle could do. Let's say when it's on, the specific state is set. I am not sure if this was resolved since it was raised

![image](https://user-images.githubusercontent.com/73167064/214520315-1a40619f-32dd-4346-a7a9-31c2fef9dae5.png)

@nervetattoo maybe you could help?

**Comment by alienatedsec** [comment]
I got this sorted now. Created both: helper (input_boolean - already mentioned in Readme) and automation to publish MQTT when it's toggled.

**Comment by alienatedsec** [comment]
@Strixx76 @DenisBY @ed-holland if you are interested about automations to address the following:


> * Click on Toggle to change state
> * Lock entity does not change

Create `input_boolean` helper and automation to publish via MQTT when it is toggled

> * Use entity to lock
> * Toggle does not change

Add another trigger to the above automation to update the toggle with `input_boolean.turn_off` and `input_boolean.turn_on` services. You just need to workout your payloads and change some naming.

Here it is:
```
alias: childlock_thermostat
description: ""
trigger:
  - platform: state
    entity_id:
      - input_boolean.childlock
    to: "off"
    id: "1"
  - platform: state
    entity_id:
      - input_boolean.childlock
    to: "on"
    id: "2"
  - platform: state
    entity_id:
      - lock.thermostat_bedroom_child_lock
    to: unlocked
    id: "3"
  - platform: state
    entity_id:
      - lock.thermostat_bedroom_child_lock
    to: locked
    id: "4"
condition: []
action:
  - if:
      - condition: trigger
        id: "1"
    then:
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/Thermostat_Bedroom/set
          payload: "{\"child_lock\": \"UNLOCK\"}"
          qos: "0"
  - if:
      - condition: trigger
        id: "2"
    then:
      - service: mqtt.publish
        data:
          payload: "{\"child_lock\": \"LOCK\"}"
          topic: zigbee2mqtt/Thermostat_Bedroom/set
          qos: "0"
  - if:
      - condition: trigger
        id: "3"
    then:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.childlock
    else: []
  - if:
      - condition: trigger
        id: "4"
    then:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.childlock
    else: []
mode: single
```
