### ISSUE TITLE
sensor attribute > Cannot read properties of null

### ISSUE THREAD

**Issue by JoelKle** [nervetattoo/simple-thermostat#279]
**Describe the bug**
I've added to my simple-thermostat a sensor and selected a special attribtute `preset_mode` to display.
The "preset_mode" attribute can be a string like "eco" or not set = `null`
If the attribute state is `null`, the card is not displayed.

Error message from Chrome developer tools:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'entity_id')
    at Pe (simple-thermostat.js?hacstag=158654878242:formatted:2011)
    at simple-thermostat.js?hacstag=158654878242:formatted:2434
    at Array.map (<anonymous>)
    at config.version.v.showSensors._hide (simple-thermostat.js?hacstag=158654878242:formatted:2431)
    at HTMLElement.render (simple-thermostat.js?hacstag=158654878242:formatted:2445)
    at HTMLElement.update (simple-thermostat.js?hacstag=158654878242:formatted:953)
    at HTMLElement.performUpdate (simple-thermostat.js?hacstag=158654878242:formatted:834)
    at HTMLElement._enqueueUpdate (simple-thermostat.js?hacstag=158654878242:formatted:816)
```

Once the attribute is set to "eco", the card is displayed.

**To Reproduce**
1. Add a sensor with a attribute
2. Ensure the attribute is set to `null`

**Expected behavior**
Card should be displayed.

simple-thermostat config:
```yaml
type: custom:simple-thermostat
entity: climate.wohnzimmer
label:
  temperature: Temperatur
hide:
  state: true
sensors:
  - entity: sensor.kleiner_heizkorper_heating
    name: Ventil Kleiner
  - entity: sensor.grosser_heizkorper_heating
    name: Ventil Großer
  - entity: climate.wohnzimmer
    name: Modus
    attribute: preset_mode
control:
  - hvac
```

State of entity `climate.wohnzimmer`:
```yaml
hvac_modes:
  - auto
  - heat
min_temp: 10
max_temp: 25
preset_modes:
  - boost
  - Homeassistant
current_temperature: 21.4
temperature: 20
preset_mode: null
model_type: HmIP-Heating-Group
is_group: true
friendly_name: Wohnzimmer
supported_features: 17
```

**Screenshots**

Chrome error message:
![Bildschirmfoto 2021-10-11 um 07 51 20](https://user-images.githubusercontent.com/34544090/136743901-77a7f91e-aa45-4bcb-8a83-f2e441fb4618.png)

State of entity `climate.wohnzimmer`:
![Bildschirmfoto 2021-10-11 um 07 52 10](https://user-images.githubusercontent.com/34544090/136743905-846b2aae-5865-4c63-82f0-0311dd4e0875.png)

Working version if the attribute is set to "eco":
![Bildschirmfoto 2021-10-11 um 08 42 21](https://user-images.githubusercontent.com/34544090/136744451-6d012a54-3663-43ae-9327-9fa6dd5a0824.png)

**Browser**
 - OS: Mac
 - Browser: Chrome 94.0.4606.61
 - Simple Thermostat version from browser console: 2.4.2
 - Home Assistant version: 2021.10.2

**Comment by JoelKle** [comment]
The following solved the problem for me:
```
version: 3
sensors:
  - label: Modus
    template: "{{ preset_mode }}"
```
I'm using the new version 3 syntax.
