### ISSUE TITLE
Display Horizontal swing mode

### ISSUE THREAD

**Issue by gulli1986** [nervetattoo/simple-thermostat#281]
I just cannot figure out how to display the horizontal swing mode for my HVAC.
The card is configured this way:

```
    cards:
      - type: custom:simple-thermostat
        entity: climate.ac_living_room
        header:
          toggle:
            entity: switch.ac_living_room_nanoe
            name: Nanoe
        control:
          - hvac
          - preset
          - fan
          - swing
```
However this will only show the "vertical" swing. Is there a way to display the "horizontal" swing as well?

Here are the attributes from the HVAC:

```
hvac_modes:
  - 'off'
  - heat
  - cool
  - heat_cool
  - dry
  - fan_only
min_temp: 16
max_temp: 30
fan_modes:
  - Auto
  - Low
  - LowMid
  - Mid
  - HighMid
  - High
preset_modes:
  - none
  - boost
  - eco
swing_modes:
  - Auto
  - Up
  - UpMid
  - Mid
  - DownMid
  - Down
current_temperature: 24
temperature: 22.5
fan_mode: Auto
preset_mode: none
swing_mode: Auto
horizontal_swing_mode: Auto
horizontal_swing_modes:
  - Auto
  - Left
  - LeftMid
  - Mid
  - RightMid
  - Right
friendly_name: AC Living Room
supported_features: 57
```
