### ISSUE TITLE
HA 2021.11b1: Buttons not any more visible 

### ISSUE THREAD

**Issue by KNXBroker** [nervetattoo/simple-thermostat#282]
**Describe the bug**
HA 2021.11b1 : Arrows for changing temperature not any more visible 

**To Reproduce**
1. Install card
2. Install beta

**Expected behavior**
Arrows should be visible

```yaml
# The least ammount of code possible to reproduce my error
type: custom:simple-thermostat
entity: climate.og_bad
header:
  name: Bad
control: false
sensors:
  - entity: sensor.og_bad_stellwert
    name: Stellwert
layout:
  step: row
hide:
  state: true

```

**Screenshots**
![Screenshot_20211028-072227](https://user-images.githubusercontent.com/25910703/139193279-65470348-22bf-4b6c-ac8d-c993bff7c119.png)

**Browser**
 - OS: /Win/Android
 - Browser: Chrome/Firefox/Mobile app? Chrome and android mobile app
 - Simple Thermostat version from browser console: 2.4.2
 - Home Assistant version: 2021.11b1
