### ISSUE TITLE
Remove current temperature value

### ISSUE THREAD

**Issue by lmorales1720** [nervetattoo/simple-thermostat#289]
I love the card!

It would be great to add the option to remove from the card the current temperature value, as I have a more precise thermometer installed in the room, compared to that from the air conditioner machine.

Thanks.

**Comment by ayonix** [comment]
If I understand you correctly, you already can:
```yaml
type: custom:simple-thermostat
entity: climate.some_climate
hide:
  temperature: true
```
