### ISSUE TITLE
Clicking on state and temperature

### ISSUE THREAD

**Issue by terba** [nervetattoo/simple-thermostat#299]
Clicking on extra sensors added with the ```sensors``` list works, but the default ```state``` and ```temperature``` sensors aren't clickable. Currently turning the header off makes the state history of the thermostat inaccessible, and for the temperature history I have to go elsewhere to click on the sensor there.

I would like to be able to click on this two elements.

Thanks in advance!

**Comment by rogatty** [comment]
Had the same issue and used a workaround:
```
hide:
  temperature: true
sensors:
  - entity: sensor.bedroom_temperature
    name: Temperature
```

I had to use a template to create a sensor from the climate entity attribute:
```
template:
  sensor:
    - name: Bedroom temperature
      unique_id: bedroom_temperature
      state: "{{ state_attr('climate.bedroom', 'current_temperature') }}"
      device_class: temperature
      state_class: measurement
      unit_of_measurement: '°C'
```
