### ISSUE TITLE
Make energy/power fields more flexible by simply allowing to plug in any sensor

### ISSUE THREAD

**Issue by nervetattoo** [nervetattoo/simple-thermostat#3]
```yaml
sensors:
  - entity: <my energy entity id>
     name: Energy today
  - entity: <an outdoor temperature entity>
     name: Outdoor temperature
  - entity: <power entity>
     name: Current power
```
