### ISSUE TITLE
CSS precedence for --st-mode-active-background

### ISSUE THREAD

**Issue by Swallowtail23** [nervetattoo/simple-thermostat#300]
**Describe the bug**
I think this is more just a CSS precedence thing than a bug, but end result is that what is instructed in the README does not apply.

CSS not applying when --st-mode-active-background is set. 
I have advantage air integration, and it is setting "heat_cool-color" to springgreen (eww), which means I have hideous bright green active buttons.

**To Reproduce**
Set --st-mode-active-background to anything, it does not change the colour of the active buttons. 
Set --st-active-color to anything, and it DOES change the colour of the text/icons on the buttons

**Expected behavior**
Colour set in CSS should apply to active mode button background

This is one of my thermostats (simplified):
```
      - type: custom:simple-thermostat
        style: |
          ha-card {
          --st-mode-active-background: green;
          }
        entity: climate.main_living
        layout:
          step: row
          mode:
            names: false
            icons: true
            headings: false
          sensors:
            type: table
            labels: true
        decimals: '0'
        fallback: '--'
        step_size: '1'
        header: false
        hide:
          temperature: true
          state: true
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8214128/145907794-3cc17f26-9c05-4913-beb9-c92c92dd8891.png)

**Browser**
 - OS: Win/Android
 - Browser: Chrome/Mobile app/Edge
 - Simple Thermostat version from browser console: 2.4.3
 - Home Assistant version: 2021.12.1
