### ISSUE TITLE
Icons for faults are not shown in header

### ISSUE THREAD

**Issue by powerpaul17** [nervetattoo/simple-thermostat#301]
**Describe the bug**
I added the battery status of my thermostats to the 'faults' section of the header. The icons are not shown, there is just a placeholder in the HTML.

**Expected behavior**
I want to see the status icons in the header bar.

```yaml
# The least ammount of code possible to reproduce my error
type: custom:simple-thermostat
entity: climate.bathroom
header:
  faults:
    - entity: binary_sensor.bathroom_thermostat_battery
```

**Screenshots**
![image](https://user-images.githubusercontent.com/2046162/146153760-b93d6cb5-746b-4a49-89a2-9e2d64db456a.png)

**Browser**
 - OS: Manjaro Linux
 - Browser: Firefox/Mobile App (Android)
 - Simple Thermostat version from browser console: 2.4.3
 - Home Assistant version: 2021.12.1
