### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'attributes').com

### ISSUE THREAD

**Issue by garyak** [nervetattoo/simple-thermostat#305]
**Describe the bug**
Error appears in HA log for 2021.12.6. No visible issues with the operation or rendering of the card.

`2021-12-29 09:48:12 ERROR (MainThread) [frontend.js.latest.202112270] http://homeassistant.local:8123/hacsfiles/simple-thermostat/simple-thermostat.js?hacstag=158654878243:285:19980 Uncaught TypeError: Cannot read properties of undefined (reading 'attributes')`

Card Config:

```
control:
  hvac:
    auto:
      icon: mdi:auto-fix
      name: Auto
    cool:
      icon: mdi:snowflake
      name: Cool
    heat:
      icon: mdi:fire
      name: Heat
    'off':
      icon: mdi:power
      name: 'Off'
    dry: false
  fan:
    auto:
      name: auto
    circulate:
      icon: mdi:restore
      name: circulate
    'on':
      icon: mdi:fan
      name: 'On'
decimals: '0'
fallback: 'Off'
icon: false
sensors:
  - attribute: current_humidity
    name: Humidity
    unit: ' %'
step_size: '1'
setpoints:
  temperature:
    hide: false
  target_temp_low:
    hide: true
  target_temp_high:
    hide: true
type: custom:simple-thermostat
layout:
  mode:
    names: false
    headings: false
    icons: true
entity: climate.south_zone_1
header:
  name: Kitchen
```

![stsat](https://user-images.githubusercontent.com/47036329/147686226-7552f59a-ed4f-4da8-a0c3-9842c338a3d3.jpg)

 - OS: Win10/iOS15+
 - Browser: All
 - Simple Thermostat version from browser console:  2.4.3
 - Home Assistant version: 2021.12.6
