### ISSUE TITLE
configuration question

### ISSUE THREAD

**Issue by bsp9493** [nervetattoo/simple-thermostat#310]
not really a bug, but a configuration question
I have a nest thermostat setup as follows...

```
type: custom:simple-thermostat
entity: climate.foyer_thermostat
header:
  toggle:
    entity: switch.humidifier
    name: humidifier
sensors:
  - entity: sensor.foyer_thermostat_humidity
    name: humidity
control:
  - hvac
decimals: '1'
step_size: '0.5'
layout:
  step: column

```

works great!

however, it will display the current_temperature attribute from the thermostat in 0.1 degree increments.  Is there a way I can override how the current_temperature attribute is displayed?  

Basically, I would like it to display with 0.5 degree increments.  ie 19.5, 20.0, 20.5 etc.

I know I can accomplish this with a template sensor similar to this
```
value_template: >
 {{ (((state_attr('climate.foyer_thermostat', 'current_temperature') | float) * 2) | round ) / 2 }}
```

but how do i get simple-thermostat to use this?

your help is appreciated.

dave
