### ISSUE TITLE
Cast: issue on State

### ISSUE THREAD

**Issue by Mariusthvdb** [nervetattoo/simple-thermostat#316]
**Describe the bug**

While regular Lovelace shows fine, Casting that view to a Google Hub makes the 'State' field show as
'ui.panel.lovelace.editor.card.generic.state:'

the values of all sensors and state are fine, its just the left side  Name of the State..

**To Reproduce**
1. Click on '....'
2. See error

**Expected behavior**

```yaml
# The least ammount of code possible to reproduce my error
type: custom:simple-thermostat
entity: climate.front_room
name: Front room
decimals: 1

```

**Screenshots**
Always include a screenshot

![20220225_083408738_iOS](https://user-images.githubusercontent.com/33354141/155682484-52b4266b-f2f4-4299-8a32-1e5b0e70d1af.jpg)

**Browser**
 - OS: Mac/Win/iOS/Android
 - Browser: Chrome/Firefox/Mobile app?
 - Simple Thermostat version from browser console: 
 - Home Assistant version:
