### ISSUE TITLE
How can we change color of green color

### ISSUE THREAD

**Issue by cataseven** [nervetattoo/simple-thermostat#320]
Hi,

I want to change the color of mdi:radiator-off if current temp is bigger than target temperature.
Also I want to change the color of icon: mdi:power-standby if target temp is bigger than current tempeprature.

Can you please help me?

```
type: grid
cards:
  - type: custom:simple-thermostat
    entity: climate.termostat
    header:
      name: Termostat
      icon:
        auto: hass:autorenew
        cool: hass:snowflake
        cooling: mdi:snowflake
        dry: hass:water-percent
        fan_only: hass:fan
        heat: hass:autorenew
        heating: mdi:radiator
        idle: mdi:radiator-disabled
        heat_cool: hass:fire
        'off': mdi:radiator-off
      toggle:
        entity: switch.child_lock
        name: Lock
    layout:
      step: column
      mode:
        names: true
        icons: true
        headings: true
    unit: null
    decimals: 1
    step_size: 0.5
    label:
      temperature: Room
      state: State
    hide:
      temperature: false
      state: true
    sensors:
      - entity: sensor.temperature
        name: Temperature
      - entity: sensor.humidity
        name: Humidity
    control:
      hvac:
        hvac_mode: true
        'off':
          name: false
          icon: mdi:power-standby
        heat_cool:
          name: false
          icon: mdi:power-standby
```
