### ISSUE TITLE
Temperature goes crazy up when pressing "UP" arrow' button

### ISSUE THREAD

**Issue by artucast** [nervetattoo/simple-thermostat#324]
**Describe the bug**
Sometimes, when pressing the "up" button, the values go crazy up like this 
![image](https://user-images.githubusercontent.com/70388653/159169899-9106f725-fafb-4626-9377-f9ce06afa84b.png)

Also, the arrows "up" and "down" disappear from time to time.

This is happening in all my configurated "simple thermostat"

**To Reproduce**
It happens randomly

**Expected behavior**
This shouldn't happen, the step should be the programmed one.

```
type: custom:simple-thermostat
control:
  hvac:
    cool:
      name: Frío
    heat:
      name: Calefacción
    'off':
      name: Apagado
entity: climate.living
hide:
  temperature: true
  state: true
icon: mdi:air-conditioner
label:
  state: Estado
step_size: '1'
header:
  icon: mdi:air-conditioner

```

**Browser**
 - OS: Win and Android
 - Browser: Chrome and Mobile app. I didn't check with other browsers?
 - Simple Thermostat version from browser console: 2.4.3
 - Home Assistant version: OS 7.4 and Core  2022.3.5. This has been happening for some time now.
