### ISSUE TITLE
control: show / hide issue

### ISSUE THREAD

**Issue by prowebuk** [nervetattoo/simple-thermostat#325]
Hi

Many thanks for the great cotrol.

Have noticed presets are hidden when
control:
  hvac: false
and hvac is hidden when
control:
  presets: false

**Comment by fcastilloec** [comment]
I've experienced this error

```
layout:
  mode:
    headings: false
control:
  preset: true
```

show the actual preset, and the same goes for `hvac`. Setting `control: false` did nothing.

I've solved this issue by deleting the `mode` key under `layout`. For some reason, this key was forcing everything to be shown
