### ISSUE TITLE
--st-mode-active-background doesn't work

### ISSUE THREAD

**Issue by mattdevo1** [nervetattoo/simple-thermostat#345]
**Describe the bug**
--st-mode-active-background doesn't seem to work for operation buttons, only preset buttons.

Right now it looks like there is a different color background for each mode button when active (eg. cool is blue, heat/cool is green). I would like the option to make the active button always be green.

```yaml
    type: custom:simple-thermostat
    entity: climate.hallway
    step_size: 1
    header:
      name: Thermostat
    card_mod:
      style: |
        ha-card {
        --st-font-size-title: 30px;
        --st-mode-active-color: red;
        --st-mode-active-background: green;
        }
```

**Screenshots**
<img width="980" alt="Screen Shot 2022-07-16 at 3 52 41 PM" src="https://user-images.githubusercontent.com/24498328/179374233-ab8e9cb0-e20a-4745-8897-6114b6215b43.png">

**Browser**
 - OS: Mac
 - Browser: Chrome
 - Simple Thermostat version from browser console: 2.4.3
 - Home Assistant version: 2022.7.5
