### ISSUE TITLE
Question: Ability to hide the temperature control

### ISSUE THREAD

**Issue by sarahmva** [nervetattoo/simple-thermostat#349]
Is it possible to only display the mode controls and hide the temperature adjustment?

**Comment by callacomp** [comment]
>Do you mean like this? Use setpoints and sensors

```
type: custom:simple-thermostat
entity: climate.dining_room
header: false
setpoints: false
sensors: false
layout:
  mode:
    names: true
```
