### ISSUE TITLE
Error when adjusting temp and hiding a setpoint

### ISSUE THREAD

**Issue by jheikkila920** [nervetattoo/simple-thermostat#352]
**Describe the bug**
When you hide either the high or low setpoint and try to adjust the set point, an error occurs:
Failed to call service climate/set_temreture. some but not all values in the same group of inclusion 'temerature' @ data[<temerature>]

**Expected behavior**
When hiding one of the set points, you should be able to still adjust the setpoint of unhidden setpoint.

```yaml
# The least ammount of code possible to reproduce my error
type: custom:simple-thermostat
header: false
entity: climate.ac_zone_thermostat
setpoints:
  target_temp_low: null
  target_temp_high:
    hide: true
```

**Screenshots**
![image](https://user-images.githubusercontent.com/112675668/190462019-0af81208-bdf9-464f-9e68-3df33f7106da.png)

**Browser**
 - OS: iOS/Windows
 - Browser: Chrome/Firefox/Mobile app
 - Simple Thermostat version from browser console: 2.5
 - Home Assistant version: 9.4
