### ISSUE TITLE
Possible to make it work with auto-entities?

### ISSUE THREAD

**Issue by alex-tomin** [nervetattoo/simple-thermostat#372]
[Auto-entitities](https://github.com/thomasloven/lovelace-auto-entities) would help a lot to generate multiple cards following same tempalte. Relevant if one has a setup requiring multiple similar thermostats (e.g. multi zone system). 

When I try to use it I get just entity not availbale from simple thermostat card:
![image](https://user-images.githubusercontent.com/8026849/209582596-63eb33aa-c9a7-4fb8-a278-43f1434bf5bd.png)

Auto-entities card example, producing the above error
```
type: custom:auto-entities
card:
  type: custom:simple-thermostat
filter:
  include:
    - domain: climate
``` 

When I specify property explicitly using **card_param**

```
type: custom:auto-entities
card:
  type: custom:simple-thermostat
filter:
  include:
    - domain: climate
card_param: entity
```

the error I get is a bit different (seems now an array of objects is passed)

![image](https://user-images.githubusercontent.com/8026849/209582734-ae997607-30e2-4117-b2f3-19053dc9cde2.png)

Any help with troubleshooting is appreciated. (maybe there's a simply workaround, or just a mistake in my script above, but hard to know without understanding what's happening behind the scenes.)
