### ISSUE TITLE
Preset mode names changes in 2023.1 show up as undefined names for presets in card

### ISSUE THREAD

**Issue by wigster** [nervetattoo/simple-thermostat#373]
**Describe the bug**
After upgrade to 2023.1 the card does not have a label for preset modes, but rather prints them as `ui.card.climate.preset_mode`

**To Reproduce**
See config below

**Expected behavior**
I guess this should just be called 'preset'.

```yaml
type: custom:simple-thermostat
entity: climate.trv_kids
```

**Screenshots**

<img width="380" alt="image" src="https://user-images.githubusercontent.com/10956987/210753649-73acc946-7c12-4b68-9635-89d4858ad9e6.png">

**Browser**
 - OS: Win
 - Browser: Chrome
 - Simple Thermostat version from browser console: 2.5.0
 - Home Assistant version: 2023.1

**Comment by acshef** [comment]
This was caused by this Home Assistant frontend commit: https://github.com/home-assistant/frontend/commit/0e70b866aeb369784697949539496414e64cb641
Here's the line that got removed: https://github.com/home-assistant/frontend/commit/0e70b866aeb369784697949539496414e64cb641#diff-e67939fd25c650222db710f18764d10ae69454b0e8ad680f5e10177c2db93ceaL155

**Comment by lesourcil** [comment]
Same issue

**Comment by roycwalton** [comment]
Same issue running 2023.01.04 HA.

**Comment by acmeGR** [comment]
Same issue Home Assistant 2023.1.2

**Comment by mcormick** [comment]
Not a solution, but to turn headings off in the card config:
```
layout:
  mode:
    headings: false
```
or just toggle off the slider `Show mode headings?` in the Card Configuration visual editor.

**Comment by Scoff123** [comment]
Does anyone know if this issue has already been raised on the Home Assistant frontend issues list? I had a look through but couldnt see it but may have missed as there are a few!

**Comment by acshef** [comment]
@Scoff123 I don't know that it's an "issue" on the Home Assistant side, per se. Home Assistant is working towards moving translations away from the frontend and over to the backend -- Simple Thermostat is just piggybacking on the frontend translations. This is a growing pain as Home Assistant consolidates their translations paradigm.

**Comment by davel4wa** [comment]
Same problem in HA 2023.1.7.

**Comment by B1ackCr0** [comment]
### **SOLVED**

I too had this issue:

![prepost](https://user-images.githubusercontent.com/77562444/216140227-e978e853-cee2-4c9f-8d1f-0f2069891171.png)

I looked at some of the available configuration options and had the idea of using '_name:' under the "preset" heading and it worked:

![postpost](https://user-images.githubusercontent.com/77562444/216140799-462b1aae-9d45-449f-b1be-b6bebb40ae52.png)

Mike

**Comment by prolife86** [comment]
> ### **SOLVED**
> I too had this issue:
> 
> ![prepost](https://user-images.githubusercontent.com/77562444/216140227-e978e853-cee2-4c9f-8d1f-0f2069891171.png)
> 
> I looked as some of the available configuration options and had the idea of using '_name:' under the "preset" heading and it worked:
> 
> ![postpost](https://user-images.githubusercontent.com/77562444/216140799-462b1aae-9d45-449f-b1be-b6bebb40ae52.png)
> 
> Mike

Hi Mike,

For me this does not work, it does nothing:

```
type: custom:simple-thermostat
entity: climate.toon_thermostaat
preset:
  _name: Preset Mode
```

As soon as I do an ident in front of it, it breaks:

```
type: custom:simple-thermostat
entity: climate.toon_thermostaat
  preset:
    _name: Preset Mode
```

Results in:
Configuration errors detected:
bad indentation of a mapping entry (3:9)

 1 | type: custom:simple-thermostat
 2 | entity: climate.toon_thermostaat
 3 |   preset:
-------------^
 4 |     _name: Preset Mode

**Comment by alienatedsec** [comment]
```
type: custom:simple-thermostat
entity: climate.toon_thermostaat
preset:
_name: Preset Mode
```
Wrong indent then. You need to be pedantic about your format and the order it comes. Not always but worth doing it right.

An example of working indent:
![image](https://user-images.githubusercontent.com/73167064/216284067-9a2c461a-62cd-4adb-8fa6-228ebbf3c63d.png)

An example of not working indent:
![image](https://user-images.githubusercontent.com/73167064/216284309-67379d6a-94df-48b2-afa4-20bec5b5695e.png)

**Comment by prolife86** [comment]
Thank you! @alienatedsec !

Solved it by adding "control" and "hvac" (to keep operation in there, else "operation"disappears and only shows presets):
my current code:
```
type: custom:simple-thermostat
entity: climate.toon_thermostaat
control:
  hvac: false
  preset:
    _name: Preset Mode
```

**Comment by finder39** [comment]
@alienatedsec I'm having some trouble as well. For some reason mine won't gain the proper name back even with the `_name` trick :/

<img width="411" alt="image" src="https://user-images.githubusercontent.com/518673/217151145-36bb34eb-2275-46bb-abe6-678a2dfe228d.png">

<img width="496" alt="image" src="https://user-images.githubusercontent.com/518673/217151197-879beae0-049f-479c-b562-2c52a6475a3d.png">

**Comment by fila612** [comment]
short question: what about the preset itself? I have a wth-2 with following presets:
preset_modes:
  - boost
  - none
  - week_program_1
  - week_program_2
  - week_program_3
  - week_program_4
  - week_program_5
  - week_program_6

can I change these names into shorter names?

**Comment by finder39** [comment]
@fila612 handle those like this:

```
      - type: 'custom:simple-thermostat'
        entity: climate.mjolnir_hvac_climate_system
        name: Climate
        control:
          hvac:
            'heat_cool':
              name: "Heat/Cool"
          preset:
            _name: Preset Mode
            'normal':
              name: 'Normal'
            'defrost':
              name: 'Defrost'
            'week_program_1':
              name: 'P1'
```

**Comment by fila612** [comment]
perfect! Thank you so much :)

**Comment by scstraus** [comment]
I'm having the same issue except for on the sensors: section as below. Any ideas?

```
    - type: custom:simple-thermostat
      entity: climate.entrance
      step_size: 0.5
      header: false
      sensors:
        - attribute: preset_mode
          name: Mode
```

<img width="399" alt="image" src="https://user-images.githubusercontent.com/7644023/233725935-9fe330af-d03c-4e2e-b65c-6b4ef7178066.png">
