### ISSUE TITLE
Can't get sensors to display

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [nervetattoo/simple-thermostat#376]
**Describe the bug**
Sensors added in the configuration don't show up in the frontend

**To Reproduce**
Add a sensor to the configuration

**Expected behavior**
I would expect the sensor entity to be displayed

```yaml
# The least ammount of code possible to reproduce my error
  - type: custom:simple-thermostat
    entity: climate.heater_test
    name: Test
    sensors:
      - entity: heater_test_valve
        name: Valve
        unit: '%'
```

**Screenshots**
![Test](https://user-images.githubusercontent.com/15329329/211821413-a0b52948-879a-4593-a793-a45c6f14bac5.PNG)

**Browser**
 - OS: Win/iOS
 - Browser: Firefox/Mobile app
 - Simple Thermostat version from browser console: 2.5.0
 - Home Assistant version: 2022.11.4
