### ISSUE TITLE
change mode headings' names?

### ISSUE THREAD

**Issue by ignacio82** [nervetattoo/simple-thermostat#384]
Is it possible to change the mode headings' names? My card looks like this:

![image](https://user-images.githubusercontent.com/1833309/228584610-a9847d45-9001-4e0f-bfba-22859429a77e.png)

and this is the code i have for it:

```
type: custom:simple-thermostat
entity: climate.first_floor_hallway
layout:
  step: row
  mode:
    names: true
    icons: true
    headings: true
header: false
control:
  - hvac
  - fan
  - preset
sensors:
  - attribute: fan_modes
    name: Fan
```

I tried using `sensors:` to rename the heading for the fan, but it did not work. Thanks for the help.

**Comment by sreknob** [comment]
This appears to be an issue since 2023.1

https://community.home-assistant.io/t/lovelace-simple-thermostat-card/82659/913

The workaround is manually assigning a label using `_name:`

```
type: custom:simple-thermostat
entity: climate.first_floor_hallway
layout:
  step: row
  mode:
    names: true
    icons: true
    headings: true
header: false
control:
  hvac: true
  fan:
    _name: Fan Mode
  preset:
    _name: Preset Mode
sensors:
  - attribute: fan_modes
    name: Fan
```
