### ISSUE TITLE
Hide everything besides Preset

### ISSUE THREAD

**Issue by lkshck** [nervetattoo/simple-thermostat#388]
Hey, I want to hide everything of the controls besides the Preset. Currently only the temperature change option is still there and I don't find any option to hide it. Goal is to set only the Preset mode from the Default Dashboard.
<img width="496" alt="grafik" src="https://user-images.githubusercontent.com/46962619/232711453-ee04179c-bd80-4162-a130-b94f8e4c7681.png">

**Comment by cfergeau** [comment]
I hid it with
```
      hide:
        state: true
      setpoints:
        temperature:
          hide: true
```
