### ISSUE TITLE
NaN When Thermostat is not online.

### ISSUE THREAD

**Issue by amarendrapramanik** [nervetattoo/simple-thermostat#390]
**Describe the bug**

NaN displaying when Thermostat is not online, whereas this control should be disabled when the thermostat is not online.  

**To Reproduce**
1. Click on '....'
2. See error

**Expected behavior**

```yaml
# The least ammount of code possible to reproduce my error
type: 'custom:simple-thermostat'
entity: ...
```

**Screenshots**
![image](https://github.com/nervetattoo/simple-thermostat/assets/67631211/f0418e90-3277-46e5-9506-dcea026a0765)

**Browser**
 - OS: Mac/Win/iOS/Android
 - Browser: Chrome/Firefox/Mobile app?
 - Simple Thermostat version from browser console: 
 - Home Assistant version:
