### ISSUE TITLE
Preset mode display issue

### ISSUE THREAD

**Issue by bogosavljevic** [nervetattoo/simple-thermostat#391]
I am using your custom thermostat card but i have issue with Hommatic IP thermostat. on the card preset mode is note displayed properly. Its out of the box. 

![image](https://github.com/nervetattoo/simple-thermostat/assets/107751881/3c874fc1-1606-4f98-a5d4-85ac3fa69a56)

How i can remove this part or maybe it would be nice some drop down menu.

 - OS: Mac/Win/iOS
 - Browser: Chrome
 - Simple Thermostat version from browser console:  v2.5.0
 - Home Assistant version:Home Assistant 2023.5.4

Many thanks,
Dimitrije

**Comment by rVlad93** [comment]
Same here. It does this regardless of what thermostat you're using.

**Comment by joho500** [comment]
Yes, I have the same issue

**Comment by bogosavljevic** [comment]
I think this project is EOL since there is no new version for arround one year.

**Comment by joho500** [comment]
Yes you could be right. 

Solved the display problem by adding` _name:` under `preset:`. Option is described in the README.md.

`control:`
`  hvac: true`
`  preset:`
`    _name: 'text here'`

**Comment by rVlad93** [comment]
> Yes you could be right.
> 
> Solved the display problem by adding` _name:` under `preset:`. Option is described in the README.md.
> 
> `control:` ` hvac: true` ` preset:` ` _name: 'text here'`

That works. Thank you!

**Comment by pergolafabio** [comment]
how can i fix this, i see this now since 2023.9.x

![image](https://github.com/nervetattoo/simple-thermostat/assets/43251136/86d5cacd-d7fc-4278-af5e-53d1f887fe7e)


```
          - type: custom:simple-thermostat
            entity: climate.weau
            layout:
              step: row
            header: false
            control: true
            step_size: 1
```

already tried below, but didnt help ?

```
          - type: custom:simple-thermostat
            entity: climate.weau
            layout:
              step: row
            header: false
            control:
              hvac:  
                'heat': true
                preset:
                  _name: 'Aan'
                'off': true
                preset:
                  _name: 'Uit'
```
