### ISSUE TITLE
[Feature Request] Override HVAC mode service call

### ISSUE THREAD

**Issue by szerencl** [nervetattoo/simple-thermostat#396]
**Is your feature request related to a problem? Please describe.**
I want to dry out my AC unit when I turn it off by running fan mode for X amount of time.
It would be nice if this could be done by remapping the 'off' mode to a script call (and passing the configured entity) instead of calling climate.set_hvac_mode

**Describe the solution you'd like**
When pressing the Off button it would call `script.ac_turn_off_with_drying` and pass `climate.my_room` as the value of `ac_entity` to it.
```
cards:
  - type: 'custom:simple-thermostat'
    entity: climate.my_room
    service:
      'off':
        domain: script
        service: ac_turn_off_with_drying
        data:
          ac_entity: {{ entity }}
```
