### ISSUE TITLE
Sensibo: Fan controls now listed in alphabetical order

### ISSUE THREAD

**Issue by Talismanian** [nervetattoo/simple-thermostat#397]
**Describe the bug**
Basically, fan controls aren't in the order listed in config anymore, but in alphabetical order. This has occurred with HA 2023.8.0, supervisor 2023.07.1, OS 10.4, frontend 20230802.0.

**To Reproduce**
Set up your thermostat card with the fan control speeds listed for your climate entity. If they're labelled alphabetically, you will see them ordered in the same way, regardless of where you position them in the config.

**Expected behavior**
In previous versions (HA 2023.7 and earlier), the card displayed the fan speeds in order as listed in the config.

```yaml
entity: climate.downstairs
type: custom:simple-thermostat
layout:
  step: row
  mode:
    headings: false
    names: false
step_size: '1'
decimals: '0'
control:
  hvac: true
  fan:
    _hide_when_off: true
    quiet: false
    strong: false
    low:
      name: Low
      icon: mdi:fan-speed-1
    medium:
      name: Medium
      icon: mdi:fan-speed-2
    high:
      name: High
      icon: mdi:fan-speed-3
    auto:
      name: Auto
      icon: mdi:fan-auto
```

**Screenshots**
![image](https://github.com/nervetattoo/simple-thermostat/assets/28279957/29ead6eb-d4c6-458a-b737-c549c16a3a11)

(I've written in the names of the fan modes, A for auto, H for high, L for low, M for medium. Notice how they're now in alphabetical order.)

**Browser**
 - OS: Win, iOS
 - Browser: Firefox, Mobile app
 - Simple Thermostat version from browser console: 2.5.0
 - Home Assistant version: 2023.8.0
