### ISSUE TITLE
Climate operation code has appeared after HA update

### ISSUE THREAD

**Issue by gabi1324** [nervetattoo/simple-thermostat#400]
**Describe the bug**
After the 2023.9.0 HA update, the card has been showing "ui.card.climate.operation"

**Expected behavior**
"ui.card.climate.operation" shouldn't appear.

```yaml
type: custom:simple-thermostat
entity: climate.living_room
header:
  toggle:
    entity: switch.living_room_ac_jet_mode
    name: Jet
step_size: 1
sensors:
  - entity: sensor.living_room_sensor_temperature
    name: Temperature
  - entity: sensor.living_room_sensor_humidity
    name: Humidity
hide:
  temperature: true
```

**Screenshots**
![SmartSelect_20230908_172003_Home Assistant](https://github.com/nervetattoo/simple-thermostat/assets/61083655/2003b0b7-dfbc-4704-9625-1771aa07d620)

**Browser**
 - OS: Android
 - Browser: Mobile app
 - Simple Thermostat version from browser console: 2.5.0
 - Home Assistant version: 2023.9.0

**Comment by pergolafabio** [comment]
Yes, I have the same issue, not sure why this is happening...

**Comment by automaton82** [comment]
Same issue, but for mine the state is `undefined`

![Screenshot_20230908_195452_Home Assistant](https://github.com/nervetattoo/simple-thermostat/assets/4467711/6a61152b-844b-46c9-91da-3b6e0e8cff85)

Yaml:

```
cards:
  - control:
      hvac:
        heat_cool: false
    version: 3
    sensors:
      - entity: sensor.z_wave_thermostat_humidity_2
        template: '{{state.text}}%'
        label: RH
    type: custom:simple-thermostat
    header:
      name: Thermostat
      icon:
        cooling: mdi:thermometer-minus
        heating: mdi:thermometer-plus
        idle: mdi:thermometer-lines
        'off': mdi:thermometer-off
        auto: mdi:thermometer
    entity: climate.z_wave_thermostat_3
type: vertical-stack
```

**Comment by MEKadan** [comment]
Hmmm... Tried to disable "Show mode headings"?

**Comment by pergolafabio** [comment]
Is that an option on the card?

I still dont get why 2023.9 update can cause an issue on this card ?

**Comment by pergolafabio** [comment]
that option indeed removes everyhing :-)  , good enough for now

![image](https://github.com/nervetattoo/simple-thermostat/assets/43251136/c1b2b814-3977-451d-afb4-d7c3fed301fb)


```
          - type: custom:simple-thermostat
            entity: climate.weau
            layout:
              step: row
              mode:
                headings: false
            header: false
```

**Comment by MEKadan** [comment]
> Is that an option on the card?
> 
> I still dont get why 2023.9 update can cause an issue on this card ?

Bit later reply, you seem to have found it already, but yes, its there:

![image](https://github.com/nervetattoo/simple-thermostat/assets/66167932/9b838c3b-8650-49eb-8f61-5c4e29837d41)

In yaml this should be enough:

![image](https://github.com/nervetattoo/simple-thermostat/assets/66167932/565a38ce-a5d6-485c-9409-94d8ee7035bd)

Suits to me, I like it more compact, like this

![image](https://github.com/nervetattoo/simple-thermostat/assets/66167932/e7be7644-c59b-486b-ba27-a49d15c5c188)

**Comment by pergolafabio** [comment]
It's indeed a workaround , but not a fix for the issue :-)

**Comment by MEKadan** [comment]
> It's indeed a workaround , but not a fix for the issue :-)

So it is, but doesn't bother me, because I wouldn't be using those headings anyway :)

**Comment by ronaldheft** [comment]
You can set the heading title with:
```
control:
  hvac:
    _name: "Mode"
```

For example:
<img width="498" alt="SCR-20230911-koyu" src="https://github.com/nervetattoo/simple-thermostat/assets/1143112/60315286-7244-4688-a9c7-93a4b036f800">

```
- type: custom:simple-thermostat
  entity: climate.ecobee_main_floor
  header: false
  decimals: 0
  step_size: 1
  label:
    temperature: Currently
  control:
    hvac:
      _name: "Mode"
      "off":
        name: "Off"
      "heat":
        name: "Heat"
      "cool":
        name: "Cool"
      "heat_cool": false
    preset:
      _name: Preset
  sensors:
    - entity: sensor.ecobee_main_floor_humidity
      name: Humidity
```

**Comment by pergolafabio** [comment]
no, that still gives the label

**Comment by ronaldheft** [comment]
Did you clear your browser cache?

**Comment by pergolafabio** [comment]
yes, also tried incognoto
tried below like your suggestion:

The mode heading to false, then it works, but its more compact then
```
          - type: custom:simple-thermostat
            entity: climate.weau
            layout:
              step: row
              # mode:
                # headings: false
            header: false
            hvac:
              _name: "Mode"
              "off":
                name: "Off"
              "heat":
                name: "Heat"
              "cool":
                name: "Cool"
              "heat_cool": false
            preset:
              _name: Preset
```

![image](https://github.com/nervetattoo/simple-thermostat/assets/43251136/51f1f797-ec84-4a79-acf4-a6f530098874)

**Comment by pergolafabio** [comment]
ok, this fixed it

```
          - type: custom:simple-thermostat
            entity: climate.weau
            layout:
              step: row
              # mode:
                # headings: false
            header: false
            control:
              hvac:
                _name: Operation
```

**Comment by NonaSuomy** [comment]
Thank you that worked for Nest as well.
```yaml
#Nest

type: custom:simple-thermostat
entity: climate.dining_room
layout:
  step: row
header: false
control:
  hvac:
    _name: Operation
    "off":
      name: "Off"
    "heat":
      name: "Heat"
    "cool":
      name: "Cool"
    "heat_cool":
      name: "Heat & Cool"
  preset:
    _name: Preset Mode
    "none":
      name: "None"
    "eco":
      name: "Eco"
sensors:
  - entity: sensor.dining_room_humidity
    name: Humidity
```
![image](https://github.com/nervetattoo/simple-thermostat/assets/1906575/aab7c597-d095-4623-b982-eb52973ffac6)

Any idea how to capitalize State: idle (heat) etc
