### ISSUE TITLE
Can’t find a way to change font size or background colour

### ISSUE THREAD

**Issue by ic-dev21** [nervetattoo/simple-thermostat#408]
**Describe the bug**
I tried to use compact mode but everything is off center and no settings seem to work. 

I’d like the card background to turn orange when heating. 

**To Reproduce**
Copy the compact example

**Expected behavior**
I’d like smaller fonts and things to be lined up correctly 

![image](https://github.com/nervetattoo/simple-thermostat/assets/108159253/a87c3b48-0b18-4dfc-8d24-29a3ec745985)

```yaml
# The least ammount of code possible to reproduce my error

type: custom:simple-thermostat
style: |
  ha-card {
    --st-font-size-xl: 20px;
    --st-font-size-m: 16px;
    --st-font-size-title: 16px;
    --st-font-size-sensors: 26px;
    --st-spacing: 0px;
    --st-mode-active-background: 
  }
entity: climate.thermostat_cuisine
layout:
  step: row 0
  mode:
    headings: false
    names: false
    icons: false
    labels: false
header: true
control: false

```

**Screenshots**
Always include a screenshot

**Browser**
 - OS: iOs
 - Browser: app
 - Simple Thermostat version from browser console: latest
 - Home Assistant version: latest
