### ISSUE TITLE
Weird layout with none parsed texts for preset and control

### ISSUE THREAD

**Issue by cyberjunky** [nervetattoo/simple-thermostat#411]
**Describe the bug**
Wierd layout with ui.card texts:
![image](https://github.com/nervetattoo/simple-thermostat/assets/5447161/053665d7-a45f-4bb7-8ff7-55cfe086a282)

**To Reproduce**
I use below config on HA 2023, now on 2024, same issue.

**Expected behavior**
Control or Preset as text or nothing?

```yaml
  - type: custom:simple-thermostat
    entity: climate.toon
    layout:
      step: row
    header: false
    control:
      - hvac
      - preset
```

**Screenshots**
See above.

**Browser**
 - OS: Mac/Win/iOS/Android
 - Browser: MS Edge
 - Simple Thermostat version from browser console: 
 - Home Assistant version: 2024.1

**Comment by TN-1** [comment]
Also have this issue. Chromium running on Raspberry Pi OS

**Comment by fireballhh** [comment]
If you put in _name: Operation and _name: Preset it will be solved.

```
                header: null
                control:
                  hvac:
                    _name: Modus
                    'off':
                      name: Aus
                    heat:
                      name: Manuell
                    auto:
                      name: Auto
                  preset:
                    _name: Preset
                    boost:
                      name: Boost
                    none:
                      name: Kein
                    week_program_1:
                      name: WP1
                    week_program_2:
                      name: WP2
                    week_program_3:
                      name: WP3
```
