### ISSUE TITLE
invert property for faults

### ISSUE THREAD

**Issue by mr-n0cturne** [nervetattoo/simple-thermostat#412]
Hello,

**Is your feature request related to a problem? Please describe.**
Im having some tado climate binary sensors where the good state is "on" and the fault state is "off"
I only want to show these icons, if the state is "off".

i.e.: 
connection state:
on: good > hide the icon
off: bad > show the icon

**Describe the solution you'd like**
I think the easiest way would be a "invert" property

i.e.:
```
type: custom:simple-thermostat
entity: climate.arbeitszimmer
header:
  faults:
    - entity: binary_sensor.arbeitszimmer_heizkoerperthermostat_connection_state
      icon: mdi:lan-disconnect
      hide_inactive: true
      invert_state: true
```

![image](https://github.com/nervetattoo/simple-thermostat/assets/45199478/348dbf8c-0fd6-44b1-8b53-61f66db95201)
