### ISSUE TITLE
away_indefinitely being displayed

### ISSUE THREAD

**Issue by talormanda** [nervetattoo/simple-thermostat#419]
**Describe the bug**
Control --> Preset ; has a mode constantly showing called away_indefinitely and no way to make it go away

```yaml
type: custom:simple-thermostat
entity: climate.air_conditioner
layout:
  step: row
  mode:
    names: true
    icons: true
    headings: false
step_size: 1
header: true
control:
  preset:
    Home: true
    Away: true
    Sleep: true
  hvac:
    'off': true
    heat: false
    cool: true
    auto: true
    _name: Mode
  fan:
    auto:
      name: 'Fan: auto'
      icon: mdi:fan-auto
    'on':
      name: 'Fan: on'
      icon: mdi:fan
```

**Screenshots**
![image](https://github.com/nervetattoo/simple-thermostat/assets/10092964/032815a8-462f-41f1-a0d8-36563105f33f)
