### ISSUE TITLE
Using Ecobee via Homekit displays "ui.card.climate.operation" header for modes

### ISSUE THREAD

**Issue by ampersandru** [nervetattoo/simple-thermostat#420]
I connect my Ecobee via Homekit controller integration for local control within HA. My lovelace yaml as follows:
```
  - type: custom:simple-thermostat
    entity: climate.main_floor_2
    layout:
      step: row
    header: false
    control: true
```
For the Modes header, it displays the unflattering "ui.card.climate.operation"
![image](https://github.com/nervetattoo/simple-thermostat/assets/43594741/559d2d35-ad40-4e8b-93a1-fd149ddbc093)

When using the built-in ecobee integration, it does not display this. I want local control because the cloud version takes forever to respond to changes.

Is there anyway to fix this or hide that header?
