### ISSUE TITLE
Heat/Cool missing button 

### ISSUE THREAD

**Issue by dekiel123** [nervetattoo/simple-thermostat#422]
On one profile Chrome shows me "Ogrzewanie" it is "heat/cool". However, in others and in the HA app this icon is missing. How to fix it?

![11111](https://github.com/nervetattoo/simple-thermostat/assets/110169964/93b2119f-ff84-4679-92e0-d6cb92ada9d8)

```
type: custom:vertical-stack-in-card
cards:
  - type: custom:simple-thermostat
    entity: climate.termostat
    header:
      name: Termostat
      icon: mdi:thermostat
      faults:
        hide_inactive: true
    hide:
      state: true
      temperature: true
    icon:
      cool: mdi:snowflake
      heat: mdi:fire
      'off': mdi:power
    sensors:
      - entity: sensor.termostat_ustawiona_temperatura
        icon: mdi:thermometer-check
        name: Ustawiona temperatura
      - entity: sensor.termostat_aktualna_temperatura
        icon: mdi:thermometer-lines
        name: Aktualna temperatura podłogi
      - entity: sensor.termometr_w_korytarzu_na_parterze_temperatura_2
        icon: mdi:home-thermometer
        name: Aktualna temperatura pomieszczenia
    step_size: 0.1
    control:
      hvac:
        _hide_when_off: false
        'off':
          hide: true
          name: Wyłącz
        heat_cool:
          name: Ogrzewaj
          icon: mdi:fire
      fan:
        _hide_when_off: false
      swig:
        _hide_when_off: false
      preset:
        _hide_when_off: false
        program:
          name: Tryb automatyczny
    layout:
      control: false
      mode:
        headings: false
    card_mod:
      style: |
        ha-card {
         --st-font-size-title: 22px;
          }
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.termostat_ustawiona_temperatura
        name: Ustawiona
        color: '#009999'
      - entity: sensor.termostat_aktualna_temperatura
        name: Aktualna podłogi
        color: '#ff9900'
      - entity: sensor.termometr_w_korytarzu_na_parterze_temperatura_2
        name: Aktualna pomieszczenia
        color: '#00bfff'
    hours_to_show: 24
    line_width: 3
    font_size: 100
    animate: true
    show:
      name: false
      icon: false
      state: false
      fill: fade
```
Thermostat states:
```
hvac_modes:
  - "off"
  - heat_cool
  - heat_cool
min_temp: 5
max_temp: 95
target_temp_step: 0.5
preset_modes:
  - program
current_temperature: 24
temperature: 16
preset_mode: null
friendly_name: Termostat w korytarzu na parterze
supported_features: 401
```
