### ISSUE TITLE
Missing temperature sensor value

### ISSUE THREAD

**Issue by emilleszczak2** [nervetattoo/simple-thermostat#426]
**Describe the bug**
After configuring the simple-thermostat for my generic thermostat entity Temperature sensor value is missing. N/A is shown

**To Reproduce**
1. Click on '....'
2. See error

**Expected behavior**
To see the current value of generic thermostat target_sensor value.

```yaml
- platform: generic_thermostat
  name: Sypialnia
  heater: switch.ogrzewanie_sypialnia
  target_sensor: sensor.xiaomi_temp_sypialnia_temperatura
  target_temp: 20.5
  away_temp: 20.0
  sleep_temp: 20.5
  comfort_temp: 20.5
  min_temp: 18.0
  max_temp: 23.0
  min_cycle_duration:
    minutes: 10
```

```yaml
type: custom:simple-thermostat
entity: climate.sypialnia
show_header: true
control: false
step_size: '0.5'
name: Sypialnia
label:
  temperature: Temperatura
  state: Tryb
```

sensor.xiaomi_temp_sypialnia_temperatura state
```yaml
state_class: temperature
unit_of_measurement: °C
device_class: temperature
friendly_name: Temperatura w sypialni
```

**Screenshots**
![Screenshot 2024-10-03 at 10 57 03](https://github.com/user-attachments/assets/d1533d54-68cf-4b08-bbd7-6d7e05faac78)
![Screenshot 2024-10-03 at 10 58 19](https://github.com/user-attachments/assets/b87a2e70-19c4-4d22-a58a-c515abf1f8bf)

**Browser**
 - OS: Mac
 - Browser: Brave
 - Simple Thermostat version from browser console: v2.5.0
 - Home Assistant version: 2024.9.3

**Comment by Tamsy** [comment]
> ```yaml
> type: custom:simple-thermostat
> entity: climate.sypialnia
> show_header: true
> control: false
> step_size: '0.5'
> name: Sypialnia
> label:
>   temperature: Temperatura
>   state: Tryb
> ```

should read:

```yaml
type: custom:simple-thermostat
entity: climate.sypialnia
header:
  name: Sypialnia
control: false
step_size: "0.5"
hide:
  temperature: true
label:
  state: Tryb
sensors:
  - entity: sensor.xiaomi_temp_sypialnia_temperatura
    name: Temperatura
```
