### ISSUE TITLE
The card is full of bugs.

### ISSUE THREAD

**Issue by cnecrea** [nervetattoo/simple-thermostat#427]
**The card is full of bugs.**

I think this is due to the maintenance no longer being active, as I can see the card hasn't been updated in over two years. The buttons (or rather the icons) for the controls no longer appear, such as: silent, low, medium, high, full, vertical, horizontal, both. Do you have any planned updates to improve all the issues, or should we start looking for another card?

Without further ado, I want to sincerely thank you for all the work done so far. I greatly appreciate the effort and dedication you've put into the project.

**Screenshots:**
<img width="396" alt="image" src="https://github.com/user-attachments/assets/148c1f36-eec5-41b3-908c-6c9b0082a388">

**Browser**
 - OS: Mac
 - Browser: Chrome

**Home Assistant:**
 - Core: 2024.11.0
 - Supervisor: 2024.11.2
 - Operating System: 13.2
 - Frontend: 20241106.0

**Comment by Tamsy** [comment]
> The buttons (or rather the icons) for the controls no longer appear, such as: silent, low, medium, high, full, vertical, horizontal, both.

If you read the [Available configuration options](https://github.com/nervetattoo/simple-thermostat?tab=readme-ov-file#available-configuration-options) carefully you will learn how to configure those to your needs.

Like i.e.
![Simple-Thermostat-Controls](https://github.com/user-attachments/assets/c0f5eb6d-cd2f-487d-a198-ed4b187de8eb)

**Comment by cnecrea** [comment]
> > The buttons (or rather the icons) for the controls no longer appear, such as: silent, low, medium, high, full, vertical, horizontal, both.
> 
> If you read the [Available configuration options](https://github.com/nervetattoo/simple-thermostat?tab=readme-ov-file#available-configuration-options) carefully you will learn how to configure those to your needs.
> 
> Like i.e. ![Simple-Thermostat-Controls](https://private-user-images.githubusercontent.com/6210614/391233101-c0f5eb6d-cd2f-487d-a198-ed4b187de8eb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5ODM5MTcsIm5iZiI6MTczMjk4MzYxNywicGF0aCI6Ii82MjEwNjE0LzM5MTIzMzEwMS1jMGY1ZWI2ZC1jZDJmLTQ4N2QtYTE5OC1lZDRiMTg3ZGU4ZWIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMzBUMTYyMDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTdhZDg1Mjc5OTM3NDRhOGUxNTEwYjQ1ODZhN2Y5OTJlNmNkZGVkNjk1OGRiYWE0YWY1ZTMyMmIzODdiMmJhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.9Ec-O9XusyOT_fLwahxk9ULHaSWrMyROxbjO4ncb81M)



Okay. I know that perfectly well. The problem is not with the ON/OFF, HOT, COLD, FAN, etc., type controls. It’s with the second part of the controls. And I am configuring them correctly. In fact, they’ve been working correctly for the past two years until Home Assistant reached version 2024.05.* (if I’m not mistaken). 

<img width="800" alt="image" src="https://github.com/user-attachments/assets/e84af4ab-67bc-4ae7-9baa-90b4e9d09524">


These are the details of the card. Everything is correct:

```
type: custom:simple-thermostat
entity: climate.romstal
name: Climate
step_size: 0.5
hide:
  temperature: true
  state: true
header: false
layout:
  mode:
    headings: false
    names: true
    icons: true
control:
  hvac:
    "off":
      name: Oprire
      icon: mdi:power
    auto:
      name: Automat
      icon: mdi:autorenew
    cool:
      name: Răcire
      icon: mdi:snowflake-alert
    dry:
      name: Umiditate
      icon: mdi:air-filter
    heat:
      name: Încălzire
      icon: mdi:heat-wave
    fan_only:
      name: Ventilator
      icon: mdi:fan
  preset:
    none:
      name: None
    comfort:
      name: Comfort
      icon: mdi:clock-alert-outline
    eco:
      name: Eco
      icon: mdi:leaf
    boost:
      name: Boost
      icon: mdi:weather-windy
    sleep:
      name: Night
      icon: mdi:sleep
    away:
      name: Away
      icon: mdi:home-off

```


```
type: custom:simple-thermostat
entity: climate.romstal
name: Climate
step_size: 0.5
hide:
  temperature: true
  state: true
header: false
layout:
  mode:
    headings: false
    names: true
    icons: true
control:
  fan:
    Silent:
      name: Silențios
      icon: mdi:volume-off
    Low:
      name: Scăzut
      icon: mdi:fan-speed-1
    Medium:
      name: Mediu
      icon: mdi:fan-speed-2
    High:
      name: Înalt
      icon: mdi:fan-speed-3
    Full:
      name: Deplin
      icon: mdi:fan-alert
    Auto:
      name: Auto
      icon: mdi:fan-auto
  swing:
    "Off":
      name: "Off"
      icon: mdi:fan-off
    Vertical:
      name: Vertical
      icon: mdi:compare-vertical
    Horizontal:
      name: Orizontal
      icon: mdi:compare-horizontal
    Both:
      name: Ambele
      icon: mdi:fan-auto

```
