### ISSUE TITLE
Values are being displayed decimal place14 should round up or have a fixed decimal of 2

### ISSUE THREAD

**Issue by TeckPete** [nervetattoo/simple-thermostat#428]
**Describe the bug**
Values are being displayed "13. 985315498548 h" should be like 13.98 h rounded or fixed decimal. See attached pictures to see what other card are reporting vs simple-thermostat card is

**To Reproduce**
1. Click on '....'
2. See error

**Expected behavior**
See the values 13.98 h  accuracy_decimals: 2 See attached pictures to see what other card are reporting vs simple-thermostat card is 

```type: custom:simple-thermostat
entity: climate.home
step_size: null
sensors:
  - entity: sensor.hvac_idle_today
  - entity: sensor.hvac_cooling_today
  - entity: sensor.hvac_heating_today
layout:
  mode:
    icons: true
    names: true
    headings: false
```
```
sensor:
  - platform: history_stats
    name: Hvac Cooling Today
    unique_id: Hvac Cooling Today
    entity_id: sensor.hvac_action
    state: "cooling"
    type: time
  
    start: "{{ now().replace(hour=0, minute=0,second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: Hvac Heating Today
    unique_id: HvacHeatingToday
    entity_id: sensor.hvac_action
    state: "heating"
    type: time
    start: "{{ now().replace(hour=0, minute=0,second=0) }}"
    end: "{{ now() }}"
    
    
  - platform: history_stats
    name: Hvac Idle Today
    unique_id: HvacIdleToday
    entity_id: sensor.hvac_action
    state: "idle"
#    type: time
    start: "{{ now().replace(hour=0, minute=0,second=0) }}"
    end: "{{ now() }}"
```
**Screenshots**
Always include a screenshot
![Capture714](https://github.com/user-attachments/assets/f78b1182-2b08-4475-8b1b-1a1ed2ee15b2)
![Capture713](https://github.com/user-attachments/assets/b751e2c2-7698-4b1f-93d4-d01925d3f7d7)
![Capture712](https://github.com/user-attachments/assets/bc0c3e3f-99f2-49ca-9f14-9d18f24b4e25)

**Browser**
 - OS: Mac/Win/iOS/Android win
 - Browser: Chrome/Firefox/Mobile app? both
 - Simple Thermostat version from browser console: latest 
 - Home Assistant version:  11
