### ISSUE TITLE
Heat Button cant be renamed or Icon

### ISSUE THREAD

**Issue by comet424** [nervetattoo/simple-thermostat#430]
**Describe the bug**
you can not change the word "Heat" to anything else 
icon doesnt change either

**To Reproduce**
control:
  hvac:
    some_mode: false
    another_mode: false
    "off":
      name: "Off"
      icon: mdi:power
    "on":
      name: "Furnace On"
      icon: mdi:power

**Expected behavior**
i should be able to change the word "HEAT"  to "Furnace On"   but you cant.. you can change "off:"  but you cant change "on:"

```yaml
# The least ammount of code possible to reproduce my error
type: 'custom:simple-thermostat'
entity: ...
```
![simple1](https://github.com/user-attachments/assets/07b7dbe9-b8c2-4149-9f4d-5e9ae15b2bdc)

**Screenshots**
Always include a screenshot

**Browser**
 - OS: Mac/Win/iOS/Android
 - Browser: Chrome/Firefox/Mobile app?
 - Simple Thermostat version from browser console: 
 - Home Assistant version:
- All browsers  on Windows and Ubuntu 
- IE, Chrome,
- v2.5.0 of simple thermosate
- HA 2024.12.4

**Comment by lmagyar** [comment]
Use "heat" instead of "on", because the thermostat state is heat, when it is "on" ie. enabled (whether the switch is on, that is in an attribute, different story).

```
type: custom:simple-thermostat
entity: climate.moms_furnace
layout:
  mode:
    headings: false
    names: true
    icons: true
control:
  hvac:
    some_mode: false
    another_mode: false
    "off":
      name: Furnace Off
      icon: mdi:power-off
    heat:
      name: Furnace On
      icon: mdi:power
  preset:
    away:
      name: NOT HOME
    none:
      name: HOME
```

![Image](https://github.com/user-attachments/assets/e6f54459-bdde-4bcf-84b2-8fd1ab668f4a)
