### ISSUE TITLE
Away_Temp over writes Target_Temp when rebooted when set Away

### ISSUE THREAD

**Issue by comet424** [nervetattoo/simple-thermostat#432]
**Describe the bug**
if you set to Away Mode  say 8 degrees and reboot home assistant  it records Target Temp for Home as 8 degrees  when you leave out target temp in the yaml.. so you can retain new setting after each reboot

**To Reproduce**
to produce  just set the button to Away  and reboot  now the home preset is the same temp
you should be able to retain new temperatures set of target and away seperately.. and when reboot they retain them seperately

**Expected behavior**
away_temp over writting target_temp

```yaml
# The least ammount of code possible to reproduce my error
type: 'custom:simple-thermostat'
entity: ...
```

**Screenshots**
Always include a screenshot

**Browser**
 - OS: Mac/Win/iOS/Android
 - Browser: Chrome/Firefox/Mobile app?
 - Simple Thermostat version from browser console: 
 - Home Assistant version:
all Browsers
latest thermostate version
and latest home assistant
