### ISSUE TITLE
Font Temperature target

### ISSUE THREAD

**Issue by Simonz82** [nervetattoo/simple-thermostat#435]
**Describe the bug**
I tried entering the code, but there is no way to reduce the size of the temperature I apply to the air conditioner

as you can see from the photo, I wanted to align the temperature size with the card to the left of it

![Image](https://github.com/user-attachments/assets/2d8c6b53-4657-4857-b4eb-1c68ea38493a)

```yaml
      - type: custom:simple-thermostat
        entity: climate.daikin_salone_temperature
        layout:
          step: row
        header: false
        control: false
        decimals: "0"
        hide:
          temperature: true
          state: true
        style: |
          ha-card {
            --st-font-size-xl: 10px; #this is a font size, but don't change
            --st-font-size-m: 10px;
            --st-font-size-title: 10px;
            --st-font-size-sensors: 10px;
            --st-spacing: 2px;
          }
```

**Browser**
 - OS: Win
 - Browser: Edge
 - Simple Thermostat version from browser console: 2.5
 - Home Assistant version:Core
2025.2.5
Supervisor
2025.03.0
Operating System
14.2
Frontend
20250221.0
