### ISSUE TITLE
multiple decimal points when changing temperature

### ISSUE THREAD

**Issue by dheath73** [nervetattoo/simple-thermostat#45]
When amending the temperature from the simple Thermostat card (see below for configuration) I'm sometimes getting multiple decimal places, please see attached screenshot below.
```
type: 'custom:simple-thermostat'
step_size: 0.1
decimals: 1
entity: climate.garden_room
hide:
  - away: false
sensors:
  - entity: input_boolean.gardenroom_virtual_heaters
    name: Virtual Heaters
  - entity: switch.garden_room_heat_1
    name: Kitchen End
  - entity: switch.garden_room_heat_2
    name: Lounge End
```
![image](https://user-images.githubusercontent.com/34939165/55554614-26c85300-56db-11e9-8412-a61f7924df1c.png)

Truly loving this thermostat and thank you for all your hard work.
