### ISSUE TITLE
Customisable font sizes for card title, entities and target temperature. 

### ISSUE THREAD

**Issue by aheath70** [nervetattoo/simple-thermostat#48]
Like this card way better than the stock thermostat card - awesome work.
I would really like to be able to customise the font sizes used. The card title and target temperature are quite large and the custom entities (like current temp) are a little too small.

**Comment by nervetattoo** [comment]
Let me know if the docs added in 0.23 is sufficient. It also moves the sensor values font size into a CSS var while also slightly increasing that font size as I realised I agreed that it was a teeny weeny bit small :)

**Comment by aheath70** [comment]
I have no the slightest idea how to use these. Could you supply an example of how to use these variables to modify the styling of the card? Or do I need to create a whole new theme for this?

Sorry for the NOOB reply.

-------------------
Andrew Heath

________________________________

**Comment by flyboy013** [comment]
I'm trying to change the size of the target temperature.  The documentation update helped, but I wasn't successful.   I tried wrapping the simple-thermostat card in card-modder to change the font size, but this didn't work.  Can you provide insight or example?


```
      - type: custom:card-modder
        style:
          --paper-font-display3_-_font-size: 32px
        card:
          type: 'custom:simple-thermostat'
          name: Living Room
          entity: climate.living_room

```

**Comment by nervetattoo** [comment]
You need to change the vars listed in the first column in the docs. Like this for example:

```yaml
type: custom:card-modder
style:
  --st-font-size-xl: 20px
card:
  type: custom:simple-thermostat
```

How can I make this clearer? Should I just remove the default value or move it as the last column instead?
