### ISSUE TITLE
Icons not being shown

### ISSUE THREAD

**Issue by syphernl** [nervetattoo/simple-thermostat#72]
My config with the latest 0.26:
```yaml
  - type: custom:simple-thermostat
    entity: climate.thermostat
    title: Woonkamer
    sensors:
      - entity: sensor.house_average_humidity
        icon: mdi:water
      - entity: sensor.house_average_temperature
        icon: mdi:thermometer
    control:
      _names: false
      hvac:
        'off':
          icon: mdi:power-standby
        'heat':
          icon: mdi:radiator
      preset:
        none:
          icon: mdi:autorenew
        away:
          icon: mdi:walk
        eco:
          icon: mdi:leaf
        'Away and Eco':
          icon: mdi:exit-run 
```

This shows up as:
![image](https://user-images.githubusercontent.com/639906/66848423-5652f480-ef75-11e9-99e4-704b10a28e3a.png)

I would expected it to show the icons I configured. HVAC simply shows the icons it wants to show while the presets simply don't show up at all.

These are my `climate.woonkamer` attributes:
```
hvac_modes: heat,off
current_temperature: 21
min_temp: 9
max_temp: 32
temperature: 20
hvac_action: idle
preset_mode: none
preset_modes: none,away,eco,Away and Eco
friendly_name: Woonkamer
supported_features: 17
```

I mapped the `hvac` controls to the ones listed in `hvac_modes` attribute and the `preset` controls as what's listed in the `preset_modes` attribute.

If I disable `_names: false` it looks like this:

![image](https://user-images.githubusercontent.com/639906/66848777-f577ec00-ef75-11e9-9d71-50e30b0164a8.png)
