### ISSUE TITLE
display issues

### ISSUE THREAD

**Issue by ciB89** [nervetattoo/simple-thermostat#83]
I just updated to latest version and now for whatever reason "heat" and "off" is swapped in my card and I don't know why and I don't like it. The second weird issue is that one of my icons is not displayed anymore although it should be displayed (when its 'heating' it should display the heat symbol). It works with the other states ('off', idle) AND it works with all my other cards AND if I change the climate device in the card, the icon shows straight away although which icon should be displayed is not linked to a sensor that was not touched.. I post my config below:

```
card:
  control:
    _headings: false
    hvac:
      heat:
        icon: 'mdi:sync'
        name: Automatik
      'off':
        icon: 'mdi:sync-off'
        name: Manuell
  entity: climate.wohnzimmer
  hide:
    away: true
    state: true
    temperature: false
  icon:
    heat: '${vars[0] === ''Heating'' ? ''mdi:fire'' : ''mdi:leaf''}'
    idle: '${vars[0] === ''Heating'' ? ''mdi:fire'' : ''mdi:leaf''}'
    'off': 'mdi:sync-off'
  sensors:
    - entity: timer.wohnzimmer_manual
    - entity: sensor.climate_wohnzimmer_status
      name: Status
    - entity: sensor.silvercrest_wohnzimmer_heating
      name: Ventil
    - entity: sensor.0x00158d0002478702_humidity
      name: Humidity
    - entity: binary_sensor.people_away
  step_size: 0.5
  type: 'custom:simple-thermostat'
entities:
  - sensor.climate_wohnzimmer_status
  - sensor.wohnzimmer_manual
  - sensor.silvercrest_wohnzimmer_heating
  - sensor.thermometer
  - sensor.thermometer_humidity
  - climate.wohnzimmer
type: 'custom:config-template-card'
variables:
  - 'states[''sensor.climate_wohnzimmer_status''].state'
  - 'states[''timer.wohnzimmer_manual''].attributes.remaining'
```

How it looks with climate.wohnzimmer and climate.bad:

https://pasteboard.co/IGnfE0W.png
