### ISSUE TITLE
How change Temperature and state

### ISSUE THREAD

**Issue by pepeEL** [nervetattoo/simple-thermostat#84]
How i can change value to translate to my language items TEMPERATURE and STATE ?

**Comment by pepeEL** [comment]
Anybody can help....?

**Comment by nervetattoo** [comment]
Possible in config thanks to https://github.com/nervetattoo/simple-thermostat/pull/82

```yaml
label:
  temperature: Temp
  state: Something
```
