### ISSUE TITLE
Hide Dry function

### ISSUE THREAD

**Issue by anhnvme** [nervetattoo/simple-thermostat#85]
Hello everybody,

How can i hide dry, fan, auto funtion ?
At swing function, i have 4 option, how can i show only, on/off

Thanks,

**Comment by nervetattoo** [comment]
This is [documented here](https://github.com/nervetattoo/simple-thermostat#example-usage)

```yaml
control:
  swing:
    some_mode_you_dont_want: false
```

.... and so on
