### ISSUE TITLE
Show control presets not in preset_modes

### ISSUE THREAD

**Issue by jjlawren** [nervetattoo/simple-thermostat#96]
It seems that I can only show presets listed in `preset_modes` on the entity. I have an Ecobee thermostat with `preset_modes` value of `['Away', 'Home', 'Sleep']`. I also want to show when `preset_mode` == "temp", which indicates a manual temperature override is set.

I've tried this with no success:
```
control:
  preset:
    Away: true
    Home: true
    Sleep: true
    temp:
      name: Hold
```
Should this be possible with a different config today?
